

export const response = {
  "success": true,
  "message": "get shipment success",
  "data": {
    "_items": [
      {
        "id": 1,
        "shipment_code": "J42T0V",
        "warehouse_tags": "6D5AJL,51W328,A80OZ8,KQ009G",
        "total_weight": 84891,
        "warehouse_send_id": 20,
        "customer_id": 17,
        "receiver_email": "strinh@yahoo.com",
        "receiver_name": "Nhâm Châu",
        "receiver_phone": "038 640 3927",
        "receiver_address": "62 Phố Phó Hiển Kỳ, Phường 7, Huyện Thu Diệp\r\nBình Định",
        "receiver_country_id": 1,
        "receiver_country_name": "Viet Nam",
        "receiver_province_id": 3,
        "receiver_province_name": "Hồ Chí Minh",
        "receiver_district_id": 68,
        "receiver_district_name": "Hải Phòng",
        "receiver_post_code": "58225-7713",
        "receiver_address_id": 81,
        "note_by_customer": "March Hare, 'that \"I like what I get\" is the same thing a Lobster Quadrille is!' 'No, indeed,'.",
        "note": "Alice!' she answered herself. 'How can you learn lessons in the schoolroom, and though this was of very little use, as it went. So she began again. 'I wonder what CAN have happened to you? Tell us.",
        "shipment_status": "NEW",
        "total_shipping_fee": "39265.00",
        "total_price": "69598.00",
        "total_cod": "29397.00",
        "total_quantity": 458581,
        "is_hold": 0,
        "is_insurance": 0,
        "courier_code": 0,
        "courier_logo": "https://lorempixel.com/150/150/?",
        "courier_estimate_time": "1376288226",
        "list_old_shipment_code": null,
        "created_at": "2015-06-23 16:07:46",
        "updated_at": "1978-02-22 08:40:24",
        "version": "4.0",
        "customer": {
          "id": 17,
          "first_name": "Huy",
          "last_name": "Chế",
          "email": "nuong.han@han.info",
          "phone": "072-181-0176",
          "username": "danh.bang",
          "password_hash": "$2y$13$2OTwPYEI4Sa7stAxlFM3Oe7S48Vi7.iKVAOd6KmbPISfPlvkc/3Gm",
          "gender": 0,
          "birthday": "1983-06-30 00:00:00",
          "avatar": "https://lorempixel.com/640/480/?44678",
          "link_verify": "http://www.tra.com.vn/doloribus-ex-ipsam-iusto-ad-at-et",
          "email_verified": 0,
          "phone_verified": 1,
          "last_order_time": "1996-05-14 18:22:29",
          "note_by_employee": "I'd taken the highest tree in front of them, and all would change to tinkling sheep-bells, and the sounds will take care of themselves.\"' 'How fond she is such a capital one for catching mice--oh, I.",
          "type_customer": 1,
          "access_token": "hTSZzqQqZmbv6yd_x7SYPmreF3Ft5z0T",
          "auth_client": "fsbhYlKLhp27xyzBCyi_aud-YwYngCkI",
          "verify_token": "vhddp-foxVIQpYzEbouHREnZPvoTJq1F",
          "reset_password_token": "wC2hNuok4UyrkTBg5JkcIXNgZ90040Kv",
          "store_id": 1,
          "active_shipping": 0,
          "total_xu": "0.0",
          "total_xu_start_date": null,
          "total_xu_expired_date": null,
          "usable_xu": "0.00",
          "usable_xu_start_date": null,
          "usable_xu_expired_date": null,
          "last_use_xu": "0.00",
          "last_use_time": null,
          "last_revenue_xu": "0.00",
          "last_revenue_time": null,
          "verify_code": "Est.",
          "verify_code_expired_at": "819869889",
          "verify_code_count": 2,
          "verify_code_type": "",
          "created_at": "134930701",
          "updated_at": "1132255148",
          "active": 1,
          "remove": 1,
          "version": "4.0"
        },
        "packageItems": []
      },
      {
        "id": 2,
        "shipment_code": "I7HI74",
        "warehouse_tags": "H2060U,03G373,42F035,I6PV59",
        "total_weight": 67941,
        "warehouse_send_id": 33,
        "customer_id": 47,
        "receiver_email": "cuc62@bao.mil.vn",
        "receiver_name": "Cụ. Chử Quảng Giáp",
        "receiver_phone": "026-657-3899",
        "receiver_address": "5100 Phố Mạch Dương Tuệ, Phường 50, Huyện Vọng\r\nHưng Yên",
        "receiver_country_id": 1,
        "receiver_country_name": "Viet Nam",
        "receiver_province_id": 9,
        "receiver_province_name": "Hà Nội",
        "receiver_district_id": 20,
        "receiver_district_name": "Hà Nội",
        "receiver_post_code": "36322-9094",
        "receiver_address_id": 16,
        "note_by_customer": "King, who had been anything near the door as you can--' 'Swim after them!' screamed the Pigeon. 'I.",
        "note": "When the Mouse only shook its head impatiently, and said, very gravely, 'I think, you ought to be ashamed of yourself,' said Alice, whose thoughts were still running on the bank, and of having the.",
        "shipment_status": "PICKUP",
        "total_shipping_fee": "916580.00",
        "total_price": "827762.00",
        "total_cod": "453811.00",
        "total_quantity": 704241,
        "is_hold": 0,
        "is_insurance": 0,
        "courier_code": 0,
        "courier_logo": "https://lorempixel.com/150/150/?",
        "courier_estimate_time": "1121473345",
        "list_old_shipment_code": null,
        "created_at": "1993-03-21 20:59:20",
        "updated_at": "1970-11-25 02:55:15",
        "version": "4.0",
        "customer": null,
        "packageItems": []
      },
      {
        "id": 3,
        "shipment_code": "VN2P4K",
        "warehouse_tags": "2GBY19,JC8374,BUGO03,0Z90J5,6ID5VQ,K2G2B2",
        "total_weight": 4396,
        "warehouse_send_id": 50,
        "customer_id": 88,
        "receiver_email": "xdanh@yahoo.com",
        "receiver_name": "Sử Nhã Trà",
        "receiver_phone": "0186 566 6564",
        "receiver_address": "8 Phố Bình Khiêm Hiếu, Xã Nương Tô, Huyện Danh\r\nĐà Nẵng",
        "receiver_country_id": 1,
        "receiver_country_name": "Viet Nam",
        "receiver_province_id": 15,
        "receiver_province_name": "Cần Thơ",
        "receiver_district_id": 39,
        "receiver_district_name": "Đà Nẵng",
        "receiver_post_code": "44535-4846",
        "receiver_address_id": 91,
        "note_by_customer": "White Rabbit as he fumbled over the fire, stirring a large crowd collected round it: there were.",
        "note": "I know. Silence all round, if you hold it too long; and that makes them so often, of course had to kneel down on one side, to look down and looked at her hands, and she was as much as she could, for.",
        "shipment_status": "PICKUP",
        "total_shipping_fee": "600203.00",
        "total_price": "619742.00",
        "total_cod": "464948.00",
        "total_quantity": 775790,
        "is_hold": 0,
        "is_insurance": 0,
        "courier_code": 0,
        "courier_logo": "https://lorempixel.com/150/150/?",
        "courier_estimate_time": "842745249",
        "list_old_shipment_code": "G2501G",
        "created_at": "1979-05-23 10:57:50",
        "updated_at": "1998-08-21 05:06:54",
        "version": "4.0",
        "customer": null,
        "packageItems": []
      },
      {
        "id": 4,
        "shipment_code": "S00HW3",
        "warehouse_tags": "6GX85G,5286H8,089F7T,YYSQ1T",
        "total_weight": 52795,
        "warehouse_send_id": 41,
        "customer_id": 84,
        "receiver_email": "quan.ha@gmail.com",
        "receiver_name": "Từ Đức",
        "receiver_phone": "(033) 583 9700",
        "receiver_address": "2564 Phố Hiên, Phường 34, Quận Đạt Khúc\r\nĐiện Biên",
        "receiver_country_id": 1,
        "receiver_country_name": "Viet Nam",
        "receiver_province_id": 3,
        "receiver_province_name": "Hồ Chí Minh",
        "receiver_district_id": 84,
        "receiver_district_name": "Hải Phòng",
        "receiver_post_code": "06882",
        "receiver_address_id": 1,
        "note_by_customer": "Alice in a very respectful tone, but frowning and making quite a new idea to Alice, and her face.",
        "note": "Alice felt so desperate that she began nibbling at the stick, and tumbled head over heels in its hurry to change the subject of conversation. While she was now about a thousand times as large as.",
        "shipment_status": "RETURN",
        "total_shipping_fee": "993343.00",
        "total_price": "943909.00",
        "total_cod": "274185.00",
        "total_quantity": 387301,
        "is_hold": 0,
        "is_insurance": 0,
        "courier_code": 0,
        "courier_logo": "https://lorempixel.com/150/150/?",
        "courier_estimate_time": "1531586714",
        "list_old_shipment_code": null,
        "created_at": "1980-11-29 03:50:22",
        "updated_at": "2018-07-25 01:37:20",
        "version": "4.0",
        "customer": null,
        "packageItems": []
      },
      {
        "id": 5,
        "shipment_code": "42TI3G",
        "warehouse_tags": "7M3H73,F1VZL8,719A36,P31P52",
        "total_weight": 71218,
        "warehouse_send_id": 92,
        "customer_id": 84,
        "receiver_email": "khoa.ly@hoang.health.vn",
        "receiver_name": "Cô. Quách Bích Thuận",
        "receiver_phone": "0186 182 6089",
        "receiver_address": "2, Ấp Dương, Phường Tăng Vượng Thoa, Huyện 44\r\nLào Cai",
        "receiver_country_id": 1,
        "receiver_country_name": "Viet Nam",
        "receiver_province_id": 41,
        "receiver_province_name": "Hải Phòng",
        "receiver_district_id": 92,
        "receiver_district_name": "Đà Nẵng",
        "receiver_post_code": "369997",
        "receiver_address_id": 35,
        "note_by_customer": "Alice in a large one, but it had fallen into the court, arm-in-arm with the birds hurried off to.",
        "note": "ME.' 'You!' said the March Hare, 'that \"I like what I was a sound of many footsteps, and Alice could think of nothing better to say but 'It belongs to a mouse: she had looked under it, and burning.",
        "shipment_status": "PICKUP",
        "total_shipping_fee": "91350.00",
        "total_price": "296045.00",
        "total_cod": "563658.00",
        "total_quantity": 155537,
        "is_hold": 1,
        "is_insurance": 0,
        "courier_code": 0,
        "courier_logo": "https://lorempixel.com/150/150/?",
        "courier_estimate_time": "144233931",
        "list_old_shipment_code": null,
        "created_at": "1999-06-21 04:14:58",
        "updated_at": "1988-05-10 22:42:22",
        "version": "4.0",
        "customer": null,
        "packageItems": []
      },
      {
        "id": 6,
        "shipment_code": "2VU671",
        "warehouse_tags": "02SYK9,8XD4IO,98Z1V9,945SKC,Q5XZ60,WE89B8,UY1312",
        "total_weight": 26511,
        "warehouse_send_id": 81,
        "customer_id": 60,
        "receiver_email": "mien78@dng.com",
        "receiver_name": "Nông Duy Nhi",
        "receiver_phone": "(84)(94)393-7934",
        "receiver_address": "076 Phố Chế Thiên Ân, Xã Hải, Quận Tôn\r\nKon Tum",
        "receiver_country_id": 1,
        "receiver_country_name": "Viet Nam",
        "receiver_province_id": 1,
        "receiver_province_name": "Đà Nẵng",
        "receiver_district_id": 6,
        "receiver_district_name": "Hồ Chí Minh",
        "receiver_post_code": "68380",
        "receiver_address_id": 35,
        "note_by_customer": "It was high time to wash the things I used to it as far as they were trying to touch her. 'Poor.",
        "note": "The hedgehog was engaged in a confused way, 'Prizes! Prizes!' Alice had never heard of one,' said Alice. 'I wonder what you're talking about,' said Alice. 'Why, you don't even know what to do.",
        "shipment_status": "RETURN",
        "total_shipping_fee": "658294.00",
        "total_price": "872450.00",
        "total_cod": "384221.00",
        "total_quantity": 430851,
        "is_hold": 1,
        "is_insurance": 0,
        "courier_code": 0,
        "courier_logo": "https://lorempixel.com/150/150/?",
        "courier_estimate_time": "1025052559",
        "list_old_shipment_code": "B074J6",
        "created_at": "1974-03-17 15:23:15",
        "updated_at": "2007-02-04 10:55:45",
        "version": "4.0",
        "customer": null,
        "packageItems": []
      },
      {
        "id": 7,
        "shipment_code": "VLP80E",
        "warehouse_tags": "8TXZCN,YSUJE5,G98W53,4W9L5M,ME29CU,311FIM,61BCU9",
        "total_weight": 40716,
        "warehouse_send_id": 27,
        "customer_id": 35,
        "receiver_email": "l.hoa@yahoo.com",
        "receiver_name": "Bác. Châu Vinh",
        "receiver_phone": "(84)(70)696-3475",
        "receiver_address": "9 Phố Diễm, Xã Lễ, Huyện Phương\r\nBắc Ninh",
        "receiver_country_id": 1,
        "receiver_country_name": "Viet Nam",
        "receiver_province_id": 17,
        "receiver_province_name": "Hồ Chí Minh",
        "receiver_district_id": 46,
        "receiver_district_name": "Hồ Chí Minh",
        "receiver_post_code": "34104-6168",
        "receiver_address_id": 45,
        "note_by_customer": "I know!' exclaimed Alice, who was peeping anxiously into her face. 'Wake up, Alice dear!' said her.",
        "note": "So she tucked it away under her arm, with its arms and frowning at the beginning,' the King said, turning to the cur, \"Such a trial, dear Sir, With no jury or judge, would be four thousand miles.",
        "shipment_status": "NEW",
        "total_shipping_fee": "650815.00",
        "total_price": "352912.00",
        "total_cod": "416938.00",
        "total_quantity": 643333,
        "is_hold": 1,
        "is_insurance": 0,
        "courier_code": 0,
        "courier_logo": "https://lorempixel.com/150/150/?",
        "courier_estimate_time": "1296717899",
        "list_old_shipment_code": "P3MI64",
        "created_at": "2009-06-24 22:24:50",
        "updated_at": "2013-01-13 17:22:07",
        "version": "4.0",
        "customer": null,
        "packageItems": []
      },
      {
        "id": 8,
        "shipment_code": "J4HH6H",
        "warehouse_tags": "9VDE2R,CMSNAS",
        "total_weight": 51241,
        "warehouse_send_id": 87,
        "customer_id": 94,
        "receiver_email": "chuong.ngan@gmail.com",
        "receiver_name": "Ung Diệp",
        "receiver_phone": "(84)(77)025-6950",
        "receiver_address": "5 Phố Ong, Xã Tâm, Huyện Kim Sáng\r\nĐắk Lắk",
        "receiver_country_id": 1,
        "receiver_country_name": "Viet Nam",
        "receiver_province_id": 38,
        "receiver_province_name": "Đà Nẵng",
        "receiver_district_id": 99,
        "receiver_district_name": "Hà Nội",
        "receiver_post_code": "77355-6459",
        "receiver_address_id": 68,
        "note_by_customer": "Alice: he had never seen such a rule at processions; 'and besides, what would happen next. The.",
        "note": "Please, Ma'am, is this New Zealand or Australia?' (and she tried the roots of trees, and I've tried hedges,' the Pigeon in a whisper.) 'That would be the right height to be.' 'It is wrong from.",
        "shipment_status": "NEW",
        "total_shipping_fee": "691534.00",
        "total_price": "336584.00",
        "total_cod": "158823.00",
        "total_quantity": 835862,
        "is_hold": 0,
        "is_insurance": 0,
        "courier_code": 0,
        "courier_logo": "https://lorempixel.com/150/150/?",
        "courier_estimate_time": "1191533287",
        "list_old_shipment_code": null,
        "created_at": "1994-02-24 00:21:28",
        "updated_at": "1993-04-07 17:17:31",
        "version": "4.0",
        "customer": null,
        "packageItems": []
      },
      {
        "id": 9,
        "shipment_code": "Y55205",
        "warehouse_tags": "ALUK3L,NC7Q5K,8T0008,KM910X,8N9909,JAV8I1,8G2ZHT",
        "total_weight": 28665,
        "warehouse_send_id": 79,
        "customer_id": 60,
        "receiver_email": "mhy@yahoo.com",
        "receiver_name": "Thập Đôn",
        "receiver_phone": "020 336 1556",
        "receiver_address": "5453, Thôn Hán Chiến Đan, Xã 6, Huyện Đôn Trầm Thục\r\nSóc Trăng",
        "receiver_country_id": 1,
        "receiver_country_name": "Viet Nam",
        "receiver_province_id": 63,
        "receiver_province_name": "Hà Nội",
        "receiver_district_id": 17,
        "receiver_district_name": "Hồ Chí Minh",
        "receiver_post_code": "980594",
        "receiver_address_id": 90,
        "note_by_customer": "CHAPTER II. The Pool of Tears 'Curiouser and curiouser!' cried Alice (she was obliged to write.",
        "note": "YOU with us!\"' 'They were learning to draw, you know--' 'But, it goes on \"THEY ALL RETURNED FROM HIM TO YOU,\"' said Alice. 'Exactly so,' said Alice. 'I'm glad I've seen that done,' thought Alice.",
        "shipment_status": "NEW",
        "total_shipping_fee": "796829.00",
        "total_price": "554235.00",
        "total_cod": "253005.00",
        "total_quantity": 864183,
        "is_hold": 1,
        "is_insurance": 0,
        "courier_code": 0,
        "courier_logo": "https://lorempixel.com/150/150/?",
        "courier_estimate_time": "1354018376",
        "list_old_shipment_code": null,
        "created_at": "2009-09-16 04:02:03",
        "updated_at": "1989-10-05 23:21:13",
        "version": "4.0",
        "customer": null,
        "packageItems": []
      },
      {
        "id": 10,
        "shipment_code": "41W2R0",
        "warehouse_tags": "7KT4E1,97G664,72RT4N,3YZPKC,3LJS7X",
        "total_weight": 30554,
        "warehouse_send_id": 35,
        "customer_id": 72,
        "receiver_email": "idiem@gmail.com",
        "receiver_name": "Cụ. Phạm Khoa",
        "receiver_phone": "84-165-575-0035",
        "receiver_address": "05, Thôn Sử Điền Thương, Phường 84, Quận 3\r\nPhú Thọ",
        "receiver_country_id": 1,
        "receiver_country_name": "Viet Nam",
        "receiver_province_id": 58,
        "receiver_province_name": "Hồ Chí Minh",
        "receiver_district_id": 79,
        "receiver_district_name": "Cần Thơ",
        "receiver_post_code": "884885",
        "receiver_address_id": 59,
        "note_by_customer": "Dormouse, who seemed to listen, the whole court was a sound of a water-well,' said the Queen, who.",
        "note": "March Hare moved into the sky all the things between whiles.' 'Then you may nurse it a minute or two she walked sadly down the chimney?--Nay, I shan't! YOU do it!--That I won't, then!--Bill's to go.",
        "shipment_status": "PICKUP",
        "total_shipping_fee": "565146.00",
        "total_price": "610362.00",
        "total_cod": "305649.00",
        "total_quantity": 366729,
        "is_hold": 0,
        "is_insurance": 0,
        "courier_code": 0,
        "courier_logo": "https://lorempixel.com/150/150/?",
        "courier_estimate_time": "592948655",
        "list_old_shipment_code": null,
        "created_at": "2002-05-20 10:16:35",
        "updated_at": "1987-07-18 16:57:12",
        "version": "4.0",
        "customer": null,
        "packageItems": []
      },
      {
        "id": 11,
        "shipment_code": "IQH6GE",
        "warehouse_tags": "4N75TC,E61WZX,EO63C3,IUE6UL",
        "total_weight": 43743,
        "warehouse_send_id": 49,
        "customer_id": 42,
        "receiver_email": "hien06@han.vn",
        "receiver_name": "Thân Đông Thư",
        "receiver_phone": "84-218-569-3219",
        "receiver_address": "5905 Phố Thạc, Xã Phạm, Quận Minh\r\nPhú Yên",
        "receiver_country_id": 1,
        "receiver_country_name": "Viet Nam",
        "receiver_province_id": 59,
        "receiver_province_name": "Hồ Chí Minh",
        "receiver_district_id": 22,
        "receiver_district_name": "Đà Nẵng",
        "receiver_post_code": "265185",
        "receiver_address_id": 47,
        "note_by_customer": "Longitude I've got to the door, she walked off, leaving Alice alone with the Duchess, who seemed.",
        "note": "I mentioned before, And have grown most uncommonly fat; Yet you turned a corner, 'Oh my ears and the other side of the suppressed guinea-pigs, filled the air, and came back again. 'Keep your.",
        "shipment_status": "NEW",
        "total_shipping_fee": "527420.00",
        "total_price": "985144.00",
        "total_cod": "340297.00",
        "total_quantity": 274285,
        "is_hold": 1,
        "is_insurance": 0,
        "courier_code": 0,
        "courier_logo": "https://lorempixel.com/150/150/?",
        "courier_estimate_time": "1211326838",
        "list_old_shipment_code": null,
        "created_at": "1973-05-05 02:06:08",
        "updated_at": "2010-09-03 10:11:37",
        "version": "4.0",
        "customer": null,
        "packageItems": []
      },
      {
        "id": 12,
        "shipment_code": "HTF10I",
        "warehouse_tags": "5219FT,K0S1MO",
        "total_weight": 39164,
        "warehouse_send_id": 69,
        "customer_id": 1,
        "receiver_email": "liu.bao@khuu.int.vn",
        "receiver_name": "Ông. Phương Hồng",
        "receiver_phone": "(84)(27)936-4852",
        "receiver_address": "381 Phố Lư, Xã 57, Quận Hậu Khánh\r\nBắc Kạn",
        "receiver_country_id": 1,
        "receiver_country_name": "Viet Nam",
        "receiver_province_id": 45,
        "receiver_province_name": "Hồ Chí Minh",
        "receiver_district_id": 19,
        "receiver_district_name": "Hồ Chí Minh",
        "receiver_post_code": "05749",
        "receiver_address_id": 60,
        "note_by_customer": "HE taught us Drawling, Stretching, and Fainting in Coils.' 'What was THAT like?' said Alice. 'Oh.",
        "note": "Alice led the way, was the White Rabbit; 'in fact, there's nothing written on the song, perhaps?' 'I've heard something splashing about in the last word with such sudden violence that Alice quite.",
        "shipment_status": "SENT",
        "total_shipping_fee": "102181.00",
        "total_price": "124781.00",
        "total_cod": "155771.00",
        "total_quantity": 697963,
        "is_hold": 0,
        "is_insurance": 0,
        "courier_code": 0,
        "courier_logo": "https://lorempixel.com/150/150/?",
        "courier_estimate_time": "681743502",
        "list_old_shipment_code": "6KMRSM",
        "created_at": "2012-05-16 02:08:05",
        "updated_at": "2010-06-13 04:48:54",
        "version": "4.0",
        "customer": {
          "id": 1,
          "first_name": "Thương",
          "last_name": "Kiều",
          "email": "ma.lam@gmail.com",
          "phone": "0240-719-9672",
          "username": "tu53",
          "password_hash": "$2y$13$zjKMZ21TN9oICYtiURjaku4xCekmE4apmakhOpzhdQJ6q0L/QeGWe",
          "gender": 0,
          "birthday": "1980-09-24 00:00:00",
          "avatar": "https://lorempixel.com/640/480/?27197",
          "link_verify": "https://bang.biz.vn/praesentium-est-nihil-error-sed-quas-hic-vitae-minus.html",
          "email_verified": 1,
          "phone_verified": 0,
          "last_order_time": "1984-03-31 09:11:48",
          "note_by_employee": "Queen, 'Really, my dear, and that is rather a handsome pig, I think.' And she began again. 'I should have croqueted the Queen's absence, and were resting in the sun. (IF you don't know of any one.",
          "type_customer": 2,
          "access_token": "HOKvHiskzuWMmo2vtjqF7SyLQn64ZXJq",
          "auth_client": "ngx5KpIJR6odS4IdSAWbeD1Zdn_OKLjW",
          "verify_token": "PH5FO77GLB9r8uQ4bSHX52bIb6jfrMd4",
          "reset_password_token": "4sb63ffjvL1f0DE4IO5ZqMiGVOJp7Vhz",
          "store_id": 1,
          "active_shipping": 0,
          "total_xu": "0.0",
          "total_xu_start_date": null,
          "total_xu_expired_date": null,
          "usable_xu": "0.00",
          "usable_xu_start_date": null,
          "usable_xu_expired_date": null,
          "last_use_xu": "0.00",
          "last_use_time": null,
          "last_revenue_xu": "0.00",
          "last_revenue_time": null,
          "verify_code": "Sit.",
          "verify_code_expired_at": "41397471",
          "verify_code_count": 1,
          "verify_code_type": "",
          "created_at": "1476365894",
          "updated_at": "166593298",
          "active": 0,
          "remove": 1,
          "version": "4.0"
        },
        "packageItems": []
      },
      {
        "id": 13,
        "shipment_code": "88V7N5",
        "warehouse_tags": "8NSPA1,T8C26O,QCK4EP",
        "total_weight": 96297,
        "warehouse_send_id": 30,
        "customer_id": 90,
        "receiver_email": "pl@gmail.com",
        "receiver_name": "Đan Tùng",
        "receiver_phone": "84-169-077-4128",
        "receiver_address": "961, Ấp Nghi Trà, Thôn Châu Trầm, Huyện 64\r\nĐồng Tháp",
        "receiver_country_id": 1,
        "receiver_country_name": "Viet Nam",
        "receiver_province_id": 55,
        "receiver_province_name": "Đà Nẵng",
        "receiver_district_id": 86,
        "receiver_district_name": "Hồ Chí Minh",
        "receiver_post_code": "304928",
        "receiver_address_id": 13,
        "note_by_customer": "Alice, very earnestly. 'I've had nothing else to do, and in another moment, when she caught it.",
        "note": "Queen left off, quite out of the table. 'Have some wine,' the March Hare. 'I didn't mean it!' pleaded poor Alice. 'But you're so easily offended!' 'You'll get used to say \"HOW DOTH THE LITTLE BUSY.",
        "shipment_status": "RETURN",
        "total_shipping_fee": "188196.00",
        "total_price": "773479.00",
        "total_cod": "871842.00",
        "total_quantity": 54040,
        "is_hold": 0,
        "is_insurance": 0,
        "courier_code": 0,
        "courier_logo": "https://lorempixel.com/150/150/?",
        "courier_estimate_time": "1530116255",
        "list_old_shipment_code": "J63LV2",
        "created_at": "1986-08-14 08:33:12",
        "updated_at": "1979-10-18 13:52:38",
        "version": "4.0",
        "customer": null,
        "packageItems": []
      },
      {
        "id": 14,
        "shipment_code": "90UONB",
        "warehouse_tags": "870GC7,V3L1U7,EF9UA4",
        "total_weight": 42611,
        "warehouse_send_id": 28,
        "customer_id": 83,
        "receiver_email": "hoa27@yahoo.com",
        "receiver_name": "Ông. Tống Chấn Tuyền",
        "receiver_phone": "098-887-1349",
        "receiver_address": "18 Phố Quốc, Xã 40, Huyện Mẫn Giao Ngôn\r\nHà Nội",
        "receiver_country_id": 1,
        "receiver_country_name": "Viet Nam",
        "receiver_province_id": 52,
        "receiver_province_name": "Hồ Chí Minh",
        "receiver_district_id": 7,
        "receiver_district_name": "Hồ Chí Minh",
        "receiver_post_code": "81377-5707",
        "receiver_address_id": 27,
        "note_by_customer": "When the pie was all about, and shouting 'Off with her head!' about once in her French.",
        "note": "Pigeon had finished. 'As if it had made. 'He took me for his housemaid,' she said to live. 'I've seen a good many little girls of her own child-life, and the cool fountains. CHAPTER VIII. The.",
        "shipment_status": "SENT",
        "total_shipping_fee": "630524.00",
        "total_price": "463491.00",
        "total_cod": "186663.00",
        "total_quantity": 789416,
        "is_hold": 1,
        "is_insurance": 0,
        "courier_code": 0,
        "courier_logo": "https://lorempixel.com/150/150/?",
        "courier_estimate_time": "434394550",
        "list_old_shipment_code": null,
        "created_at": "1993-10-23 06:31:44",
        "updated_at": "2005-07-05 08:49:55",
        "version": "4.0",
        "customer": null,
        "packageItems": []
      },
      {
        "id": 15,
        "shipment_code": "S191K6",
        "warehouse_tags": "94OMTV,4R3B0O",
        "total_weight": 79831,
        "warehouse_send_id": 12,
        "customer_id": 62,
        "receiver_email": "phat71@son.com",
        "receiver_name": "Kiều Mỹ Hoài",
        "receiver_phone": "84-96-449-1851",
        "receiver_address": "73, Thôn 2, Phường Thân Kính Ngọc, Quận Trâm Yên\r\nHưng Yên",
        "receiver_country_id": 1,
        "receiver_country_name": "Viet Nam",
        "receiver_province_id": 2,
        "receiver_province_name": "Hà Nội",
        "receiver_district_id": 80,
        "receiver_district_name": "Hồ Chí Minh",
        "receiver_post_code": "10332-0413",
        "receiver_address_id": 62,
        "note_by_customer": "Magpie began wrapping itself up and bawled out, \"He's murdering the time! Off with his nose Trims.",
        "note": "Lobster Quadrille is!' 'No, indeed,' said Alice. 'Call it what you like,' said the White Rabbit, 'but it sounds uncommon nonsense.' Alice said to the dance. Would not, could not, could not possibly.",
        "shipment_status": "RETURN",
        "total_shipping_fee": "994642.00",
        "total_price": "20097.00",
        "total_cod": "523158.00",
        "total_quantity": 591541,
        "is_hold": 0,
        "is_insurance": 0,
        "courier_code": 0,
        "courier_logo": "https://lorempixel.com/150/150/?",
        "courier_estimate_time": "519466208",
        "list_old_shipment_code": "330TV7",
        "created_at": "2007-03-05 05:15:11",
        "updated_at": "2017-08-08 07:45:47",
        "version": "4.0",
        "customer": null,
        "packageItems": []
      },
      {
        "id": 16,
        "shipment_code": "6SK9XY",
        "warehouse_tags": "2C5Z3P,J8186D,I5O4L2,FD3PSH,0AU457",
        "total_weight": 25449,
        "warehouse_send_id": 17,
        "customer_id": 63,
        "receiver_email": "tdanh@nghi.biz",
        "receiver_name": "Ánh Nguyên",
        "receiver_phone": "(0219) 239 8500",
        "receiver_address": "59 Phố Từ, Ấp Tùng Ca, Quận Nghi\r\nBà Rịa - Vũng Tàu",
        "receiver_country_id": 1,
        "receiver_country_name": "Viet Nam",
        "receiver_province_id": 26,
        "receiver_province_name": "Đà Nẵng",
        "receiver_district_id": 96,
        "receiver_district_name": "Hà Nội",
        "receiver_post_code": "02042-8250",
        "receiver_address_id": 78,
        "note_by_customer": "When she got into it), and sometimes she scolded herself so severely as to bring but one; Bill's.",
        "note": "D,' she added in an offended tone. And the Gryphon added 'Come, let's hear some of YOUR adventures.' 'I could tell you more than nine feet high, and her face like the three gardeners instantly threw.",
        "shipment_status": "PICKUP",
        "total_shipping_fee": "873243.00",
        "total_price": "845269.00",
        "total_cod": "416773.00",
        "total_quantity": 347156,
        "is_hold": 1,
        "is_insurance": 0,
        "courier_code": 0,
        "courier_logo": "https://lorempixel.com/150/150/?",
        "courier_estimate_time": "1229973605",
        "list_old_shipment_code": null,
        "created_at": "2000-02-23 12:07:34",
        "updated_at": "2009-11-29 14:32:14",
        "version": "4.0",
        "customer": null,
        "packageItems": []
      },
      {
        "id": 17,
        "shipment_code": "X62O3M",
        "warehouse_tags": "7I180Y,00LG2E",
        "total_weight": 29502,
        "warehouse_send_id": 35,
        "customer_id": 83,
        "receiver_email": "khuyen15@yahoo.com",
        "receiver_name": "Giao Hiếu Diệu",
        "receiver_phone": "(0164) 885 7694",
        "receiver_address": "5363, Thôn 70, Xã 6, Quận Hoài Cát\r\nSơn La",
        "receiver_country_id": 1,
        "receiver_country_name": "Viet Nam",
        "receiver_province_id": 65,
        "receiver_province_name": "Cần Thơ",
        "receiver_district_id": 92,
        "receiver_district_name": "Đà Nẵng",
        "receiver_post_code": "13479",
        "receiver_address_id": 40,
        "note_by_customer": "Alice hastily replied; 'at least--at least I know I have dropped them, I wonder?' And here poor.",
        "note": "I can listen all day about it!' Last came a little feeble, squeaking voice, ('That's Bill,' thought Alice,) 'Well, I shan't grow any more--As it is, I suppose?' said Alice. 'Why, there they lay on.",
        "shipment_status": "NEW",
        "total_shipping_fee": "189731.00",
        "total_price": "348562.00",
        "total_cod": "802684.00",
        "total_quantity": 222318,
        "is_hold": 1,
        "is_insurance": 0,
        "courier_code": 0,
        "courier_logo": "https://lorempixel.com/150/150/?",
        "courier_estimate_time": "1363998882",
        "list_old_shipment_code": "009V5R",
        "created_at": "2001-12-04 19:01:54",
        "updated_at": "1999-06-04 22:21:24",
        "version": "4.0",
        "customer": null,
        "packageItems": []
      },
      {
        "id": 18,
        "shipment_code": "331IC8",
        "warehouse_tags": "X2IP9E",
        "total_weight": 54892,
        "warehouse_send_id": 25,
        "customer_id": 57,
        "receiver_email": "ngan60@ong.com",
        "receiver_name": "Chú. Hàng Hữu Tuyền",
        "receiver_phone": "058 879 0321",
        "receiver_address": "736 Phố Tông Trung Tiên, Xã 8, Huyện Thiên Lữ\r\nĐà Nẵng",
        "receiver_country_id": 1,
        "receiver_country_name": "Viet Nam",
        "receiver_province_id": 26,
        "receiver_province_name": "Đà Nẵng",
        "receiver_district_id": 49,
        "receiver_district_name": "Hải Phòng",
        "receiver_post_code": "482138",
        "receiver_address_id": 6,
        "note_by_customer": "YOU sing,' said the Dodo, 'the best way you go,' said the Dormouse, without considering at all.",
        "note": "And the Gryphon added 'Come, let's hear some of the room. The cook threw a frying-pan after her as she had to be an advantage,' said Alice, surprised at this, but at any rate: go and get ready for.",
        "shipment_status": "PICKUP",
        "total_shipping_fee": "105446.00",
        "total_price": "593145.00",
        "total_cod": "858008.00",
        "total_quantity": 15350,
        "is_hold": 1,
        "is_insurance": 0,
        "courier_code": 0,
        "courier_logo": "https://lorempixel.com/150/150/?",
        "courier_estimate_time": "147436701",
        "list_old_shipment_code": null,
        "created_at": "1978-05-21 18:10:11",
        "updated_at": "1978-07-05 17:06:46",
        "version": "4.0",
        "customer": null,
        "packageItems": []
      },
      {
        "id": 19,
        "shipment_code": "KV480A",
        "warehouse_tags": "53S3FM,V9IT7F,JJ8ZY7,R099N8,IT9RP5",
        "total_weight": 65724,
        "warehouse_send_id": 57,
        "customer_id": 22,
        "receiver_email": "xhung@gmail.com",
        "receiver_name": "Cụ. Sử Hồng Võ",
        "receiver_phone": "0167 776 4217",
        "receiver_address": "2883, Ấp Mâu Nhuận Chiến, Xã Thống, Huyện Tống\r\nBạc Liêu",
        "receiver_country_id": 1,
        "receiver_country_name": "Viet Nam",
        "receiver_province_id": 16,
        "receiver_province_name": "Cần Thơ",
        "receiver_district_id": 17,
        "receiver_district_name": "Hải Phòng",
        "receiver_post_code": "87664",
        "receiver_address_id": 2,
        "note_by_customer": "Edwin and Morcar, the earls of Mercia and Northumbria, declared for him: and even Stigand, the.",
        "note": "Mabel! I'll try and repeat \"'TIS THE VOICE OF THE SLUGGARD,\"' said the Hatter. 'I deny it!' said the March Hare. 'Sixteenth,' added the Dormouse. 'Write that down,' the King sharply. 'Do you know.",
        "shipment_status": "RETURN",
        "total_shipping_fee": "346214.00",
        "total_price": "37703.00",
        "total_cod": "29145.00",
        "total_quantity": 587062,
        "is_hold": 1,
        "is_insurance": 0,
        "courier_code": 0,
        "courier_logo": "https://lorempixel.com/150/150/?",
        "courier_estimate_time": "1252160875",
        "list_old_shipment_code": "9T032K",
        "created_at": "1973-12-16 09:56:21",
        "updated_at": "2013-03-26 07:08:30",
        "version": "4.0",
        "customer": null,
        "packageItems": []
      },
      {
        "id": 20,
        "shipment_code": "895R29",
        "warehouse_tags": "JOHL49,P40OIT,4E23V6",
        "total_weight": 7198,
        "warehouse_send_id": 97,
        "customer_id": 47,
        "receiver_email": "cu.loc@tieu.gov.vn",
        "receiver_name": "Cụ. Đường Chi Giang",
        "receiver_phone": "84-164-085-8980",
        "receiver_address": "1 Phố Nghị Cần Linh, Xã Quách Ái Thắm, Quận Thái Dương Lễ\r\nĐắk Lắk",
        "receiver_country_id": 1,
        "receiver_country_name": "Viet Nam",
        "receiver_province_id": 12,
        "receiver_province_name": "Hải Phòng",
        "receiver_district_id": 21,
        "receiver_district_name": "Hải Phòng",
        "receiver_post_code": "992537",
        "receiver_address_id": 92,
        "note_by_customer": "Where CAN I have ordered'; and she walked up towards it rather timidly, as she leant against a.",
        "note": "Mock Turtle at last, and managed to swallow a morsel of the thing yourself, some winter day, I will just explain to you how the game was going on between the executioner, the King, the Queen.",
        "shipment_status": "SENT",
        "total_shipping_fee": "706329.00",
        "total_price": "401432.00",
        "total_cod": "310105.00",
        "total_quantity": 411114,
        "is_hold": 0,
        "is_insurance": 0,
        "courier_code": 0,
        "courier_logo": "https://lorempixel.com/150/150/?",
        "courier_estimate_time": "1106785632",
        "list_old_shipment_code": null,
        "created_at": "2015-03-06 01:45:18",
        "updated_at": "2014-06-30 01:00:33",
        "version": "4.0",
        "customer": null,
        "packageItems": []
      }
    ],
    "_links": {
      "self": {
        "href": "http://weshop-4.0.api.vn/v1/s?page=1"
      }
    },
    "_meta": {
      "totalCount": 20,
      "pageCount": 1,
      "currentPage": 1,
      "perPage": 20
    }
  }
};
