

export const response = {
  "success": true,
  "message": "get shipment success",
  "data": {
    "_items": [
      {
        "id": 1,
        "shipment_code": "J42T0V",
        "warehouse_tags": "6D5AJL,51W328,A80OZ8,KQ009G",
        "total_weight": 84891,
        "warehouse_send_id": 20,
        "customer_id": 17,
        "receiver_email": "strinh@yahoo.com",
        "receiver_name": "Nhâm Châu",
        "receiver_phone": "038 640 3927",
        "receiver_address": "62 Phố Phó Hiển Kỳ, Phường 7, Huyện Thu Diệp\r\nBình Định",
        "receiver_country_id": 1,
        "receiver_country_name": "Viet Nam",
        "receiver_province_id": 3,
        "receiver_province_name": "Hồ Chí Minh",
        "receiver_district_id": 68,
        "receiver_district_name": "Hải Phòng",
        "receiver_post_code": "58225-7713",
        "receiver_address_id": 81,
        "note_by_customer": "March Hare, 'that \"I like what I get\" is the same thing a Lobster Quadrille is!' 'No, indeed,'.",
        "note": "Alice!' she answered herself. 'How can you learn lessons in the schoolroom, and though this was of very little use, as it went. So she began again. 'I wonder what CAN have happened to you? Tell us.",
        "shipment_status": "NEW",
        "total_shipping_fee": "39265.00",
        "total_price": "69598.00",
        "total_cod": "29397.00",
        "total_quantity": 458581,
        "is_hold": 0,
        "is_insurance": 0,
        "courier_code": 0,
        "courier_logo": "https://lorempixel.com/150/150/?",
        "courier_estimate_time": "1376288226",
        "list_old_shipment_code": null,
        "created_at": "2015-06-23 16:07:46",
        "updated_at": "1978-02-22 08:40:24",
        "version": "4.0",
        "customer": {
          "id": 17,
          "first_name": "Huy",
          "last_name": "Chế",
          "email": "nuong.han@han.info",
          "phone": "072-181-0176",
          "username": "danh.bang",
          "password_hash": "$2y$13$2OTwPYEI4Sa7stAxlFM3Oe7S48Vi7.iKVAOd6KmbPISfPlvkc/3Gm",
          "gender": 0,
          "birthday": "1983-06-30 00:00:00",
          "avatar": "https://lorempixel.com/640/480/?44678",
          "link_verify": "http://www.tra.com.vn/doloribus-ex-ipsam-iusto-ad-at-et",
          "email_verified": 0,
          "phone_verified": 1,
          "last_order_time": "1996-05-14 18:22:29",
          "note_by_employee": "I'd taken the highest tree in front of them, and all would change to tinkling sheep-bells, and the sounds will take care of themselves.\"' 'How fond she is such a capital one for catching mice--oh, I.",
          "type_customer": 1,
          "access_token": "hTSZzqQqZmbv6yd_x7SYPmreF3Ft5z0T",
          "auth_client": "fsbhYlKLhp27xyzBCyi_aud-YwYngCkI",
          "verify_token": "vhddp-foxVIQpYzEbouHREnZPvoTJq1F",
          "reset_password_token": "wC2hNuok4UyrkTBg5JkcIXNgZ90040Kv",
          "store_id": 1,
          "active_shipping": 0,
          "total_xu": "0.0",
          "total_xu_start_date": null,
          "total_xu_expired_date": null,
          "usable_xu": "0.00",
          "usable_xu_start_date": null,
          "usable_xu_expired_date": null,
          "last_use_xu": "0.00",
          "last_use_time": null,
          "last_revenue_xu": "0.00",
          "last_revenue_time": null,
          "verify_code": "Est.",
          "verify_code_expired_at": "819869889",
          "verify_code_count": 2,
          "verify_code_type": "",
          "created_at": "134930701",
          "updated_at": "1132255148",
          "active": 1,
          "remove": 1,
          "version": "4.0"
        },
        "warehouseSend": {
          "id": 20,
          "name": "Bác. Ông Trang",
          "description": "Yên Phụng Chưởng",
          "district_id": null,
          "province_id": 3,
          "country_id": 1,
          "store_id": 1,
          "address": "734 Phố Danh Hà Hân, Phường Trí, Huyện Hòa Giang\r\nLai Châu",
          "type": 2,
          "warehouse_group": "1",
          "post_code": "73327-3486",
          "telephone": "+84-168-772-2930",
          "email": "phan.an@gmail.com",
          "contact_person": "",
          "ref_warehouse_id": 488,
          "created_at": "1993-03-11 23:09:17",
          "updated_at": "1973-08-27 23:36:45",
          "version": "4.0"
        },
        "packageItems": [
          {
            "id": 1,
            "package_id": 489,
            "package_code": "27805932774",
            "box_me_warehouse_tag": "CB_TAG-5OF5Q3PB0624424I",
            "order_id": 908,
            "product_id": 1,
            "quantity": 196,
            "weight": 157,
            "change_weight": 39488781.6,
            "dimension_l": 402,
            "dimension_w": 751,
            "dimension_h": 654,
            "stock_in_local": "121948803",
            "stock_out_local": "1516350214",
            "at_customer": null,
            "returned": null,
            "lost": "1378062375",
            "current_status": "LOST",
            "shipment_id": 1,
            "created_at": "1996-01-02 09:39:14",
            "updated_at": "1995-04-19 12:49:37",
            "remove": 0,
            "price": 123434,
            "cod": 1223,
            "version": "4.0",
            "hold": null,
            "product": {
              "id": 1,
              "order_id": 10,
              "seller_id": 2,
              "portal": "AMAZON_JAPAN",
              "sku": "ae1c30f45962aabde7ce1062c2dada66",
              "parent_sku": "922f56b5ef99f43d5e76d194bdf674f7",
              "link_img": "https://lorempixel.com/640/480/?56801",
              "link_origin": "http://www.du.net.vn/",
              "category_id": 2,
              "custom_category_id": 2,
              "price_amount_origin": "1.00",
              "price_amount_local": "70500.00",
              "total_price_amount_local": "141000.00",
              "total_fee_product_local": null,
              "quantity_customer": 3,
              "quantity_purchase": 0,
              "quantity_inspect": 0,
              "price_purchase": null,
              "shipping_fee_purchase": null,
              "tax_fee_purchase": null,
              "variations": "",
              "variation_id": null,
              "note_by_customer": "YOUR adventures.'.",
              "total_weight_temporary": "1.00",
              "created_at": "1985-08-13 08:46:40",
              "updated_at": "1995-04-01 08:05:10",
              "remove": 0,
              "product_name": "I don't take this young lady to see the Mock Turtle. 'Certainly not!' said Alice as it spoke. 'As wet as ever,' said Alice in a very grave voice, 'until all the arches are gone from this side of the.",
              "product_link": null,
              "version": "4.0",
              "condition": null,
              "seller_refund_amount": null
            }
          },
          {
            "id": 2,
            "package_id": 69,
            "package_code": "34632519087",
            "box_me_warehouse_tag": "CB_TAG-HAA12Q030JKZS773",
            "order_id": 916,
            "product_id": 77,
            "quantity": 235,
            "weight": 291,
            "change_weight": 5167800,
            "dimension_l": 108,
            "dimension_w": 550,
            "dimension_h": 435,
            "stock_in_local": "464164561",
            "stock_out_local": null,
            "at_customer": null,
            "returned": null,
            "lost": "987563901",
            "current_status": "RETURNED",
            "shipment_id": 1,
            "created_at": "1989-07-26 08:54:10",
            "updated_at": "2010-11-05 04:22:15",
            "remove": 0,
            "price": null,
            "cod": null,
            "version": "4.0",
            "hold": null,
            "product": {
              "id": 77,
              "order_id": 104,
              "seller_id": 36,
              "portal": "EBAY",
              "sku": "15356494",
              "parent_sku": "252888606889",
              "link_img": "test",
              "link_origin": "test",
              "category_id": 51,
              "custom_category_id": null,
              "price_amount_origin": "9.05",
              "price_amount_local": "212675.00",
              "total_price_amount_local": "0.00",
              "total_fee_product_local": "307521.00",
              "quantity_customer": 1,
              "quantity_purchase": null,
              "quantity_inspect": null,
              "price_purchase": null,
              "shipping_fee_purchase": null,
              "tax_fee_purchase": null,
              "variations": null,
              "variation_id": null,
              "note_by_customer": "Note By Customer",
              "total_weight_temporary": "0.00",
              "created_at": "2019-04-10 11:21:47",
              "updated_at": "",
              "remove": 0,
              "product_name": "Mens Dri-Fit Workout Performance Moisture Wicking Gym Sport T-Shirt Dry T PC380",
              "product_link": "https://weshop.com.vn/link/sanpham.html",
              "version": "4.0",
              "condition": null,
              "seller_refund_amount": null
            }
          },
          {
            "id": 3,
            "package_id": 997,
            "package_code": "59689274816",
            "box_me_warehouse_tag": "CB_TAG-2XO542QL8CR05OV4",
            "order_id": 851,
            "product_id": 112,
            "quantity": 430,
            "weight": 565,
            "change_weight": 3091088,
            "dimension_l": 130,
            "dimension_w": 386,
            "dimension_h": 308,
            "stock_in_local": null,
            "stock_out_local": "1075275116",
            "at_customer": "1096912588",
            "returned": "799015092",
            "lost": null,
            "current_status": "STOCK_IN_LOCAL",
            "shipment_id": 1,
            "created_at": "1975-12-20 06:17:53",
            "updated_at": "2001-08-27 03:30:18",
            "remove": 0,
            "price": null,
            "cod": null,
            "version": "4.0",
            "hold": null,
            "product": {
              "id": 112,
              "order_id": 127,
              "seller_id": 59,
              "portal": "AMAZON",
              "sku": "B07C49F2LD",
              "parent_sku": "B07C49F2LD",
              "link_img": "test",
              "link_origin": "test",
              "category_id": 86,
              "custom_category_id": null,
              "price_amount_origin": "27900.00",
              "price_amount_local": "2346334200.00",
              "total_price_amount_local": "0.00",
              "total_fee_product_local": "195292375.60",
              "quantity_customer": 10,
              "quantity_purchase": null,
              "quantity_inspect": null,
              "price_purchase": null,
              "shipping_fee_purchase": null,
              "tax_fee_purchase": null,
              "variations": null,
              "variation_id": null,
              "note_by_customer": "Note By Customer",
              "total_weight_temporary": "0.00",
              "created_at": "2019-04-10 14:10:01",
              "updated_at": "",
              "remove": 0,
              "product_name": "Denon AVR-S540BT Receiver, 5.2 channel, 4K Ultra HD Audio and Video, Home Theater System, built-in Bluetooth and USB port, Compatible with HEOS Link for Wireless Music Streaming",
              "product_link": "https://weshop.com.vn/link/sanpham.html",
              "version": "4.0",
              "condition": null,
              "seller_refund_amount": null
            }
          }
        ]
      },
      {
        "id": 2,
        "shipment_code": "I7HI74",
        "warehouse_tags": "H2060U,03G373,42F035,I6PV59",
        "total_weight": 67941,
        "warehouse_send_id": 33,
        "customer_id": 47,
        "receiver_email": "cuc62@bao.mil.vn",
        "receiver_name": "Cụ. Chử Quảng Giáp",
        "receiver_phone": "026-657-3899",
        "receiver_address": "5100 Phố Mạch Dương Tuệ, Phường 50, Huyện Vọng\r\nHưng Yên",
        "receiver_country_id": 1,
        "receiver_country_name": "Viet Nam",
        "receiver_province_id": 9,
        "receiver_province_name": "Hà Nội",
        "receiver_district_id": 20,
        "receiver_district_name": "Hà Nội",
        "receiver_post_code": "36322-9094",
        "receiver_address_id": 16,
        "note_by_customer": "King, who had been anything near the door as you can--' 'Swim after them!' screamed the Pigeon. 'I.",
        "note": "When the Mouse only shook its head impatiently, and said, very gravely, 'I think, you ought to be ashamed of yourself,' said Alice, whose thoughts were still running on the bank, and of having the.",
        "shipment_status": "PICKUP",
        "total_shipping_fee": "916580.00",
        "total_price": "827762.00",
        "total_cod": "453811.00",
        "total_quantity": 704241,
        "is_hold": 0,
        "is_insurance": 0,
        "courier_code": 0,
        "courier_logo": "https://lorempixel.com/150/150/?",
        "courier_estimate_time": "1121473345",
        "list_old_shipment_code": null,
        "created_at": "1993-03-21 20:59:20",
        "updated_at": "1970-11-25 02:55:15",
        "version": "4.0",
        "customer": null,
        "warehouseSend": null,
        "packageItems": [
          {
            "id": 4,
            "package_id": 684,
            "package_code": "52841142833",
            "box_me_warehouse_tag": null,
            "order_id": 399,
            "product_id": 47,
            "quantity": 813,
            "weight": 717,
            "change_weight": 18576409.6,
            "dimension_l": 784,
            "dimension_w": 472,
            "dimension_h": 251,
            "stock_in_local": "1209312374",
            "stock_out_local": null,
            "at_customer": null,
            "returned": null,
            "lost": null,
            "current_status": "LOST",
            "shipment_id": 2,
            "created_at": "1983-12-18 02:05:30",
            "updated_at": "1972-07-12 17:45:50",
            "remove": 0,
            "price": null,
            "cod": null,
            "version": "4.0",
            "hold": null,
            "product": {
              "id": 47,
              "order_id": 50,
              "seller_id": 21,
              "portal": "",
              "sku": "IF_739F9D0E",
              "parent_sku": "252888606889",
              "link_img": "",
              "link_origin": "https://www.ebay.com/itm/Mens-Dri-Fit-Workout-Performance-Moisture-Wicking-Gym-Sport-T-Shirt-Dry-T-PC380-/252888606889?var=",
              "category_id": 36,
              "custom_category_id": null,
              "price_amount_origin": "0.00",
              "price_amount_local": "0.00",
              "total_price_amount_local": "0.00",
              "total_fee_product_local": null,
              "quantity_customer": 1,
              "quantity_purchase": null,
              "quantity_inspect": null,
              "price_purchase": null,
              "shipping_fee_purchase": null,
              "tax_fee_purchase": null,
              "variations": null,
              "variation_id": null,
              "note_by_customer": null,
              "total_weight_temporary": null,
              "created_at": "2019-04-02 13:10:11",
              "updated_at": "",
              "remove": null,
              "product_name": "",
              "product_link": null,
              "version": "4.0",
              "condition": null,
              "seller_refund_amount": null
            }
          },
          {
            "id": 5,
            "package_id": 688,
            "package_code": "59709902859",
            "box_me_warehouse_tag": "CB_TAG-JZ7RD4846K6468QN",
            "order_id": 351,
            "product_id": 2,
            "quantity": 298,
            "weight": 804,
            "change_weight": 15210426,
            "dimension_l": 803,
            "dimension_w": 154,
            "dimension_h": 615,
            "stock_in_local": null,
            "stock_out_local": "1122365554",
            "at_customer": null,
            "returned": "566608156",
            "lost": "1233600209",
            "current_status": "AT_CUSTOMER",
            "shipment_id": 2,
            "created_at": "1976-08-22 17:38:35",
            "updated_at": "1971-08-20 23:33:39",
            "remove": 0,
            "price": null,
            "cod": null,
            "version": "4.0",
            "hold": null,
            "product": {
              "id": 2,
              "order_id": 4,
              "seller_id": 2,
              "portal": "OTHER",
              "sku": "d8bffdabe3f51ce9eb29be84a64344d1",
              "parent_sku": "1737ccf1fd73f72af302ddd49d3d4535",
              "link_img": "https://lorempixel.com/640/480/?11825",
              "link_origin": "http://nhiem.net/qui-maiores-perspiciatis-cumque-qui-illo-libero-alias",
              "category_id": 4,
              "custom_category_id": 3,
              "price_amount_origin": "3.00",
              "price_amount_local": "47000.00",
              "total_price_amount_local": "94000.00",
              "total_fee_product_local": null,
              "quantity_customer": 2,
              "quantity_purchase": 0,
              "quantity_inspect": 0,
              "price_purchase": null,
              "shipping_fee_purchase": null,
              "tax_fee_purchase": null,
              "variations": "",
              "variation_id": null,
              "note_by_customer": "When the Mouse.",
              "total_weight_temporary": "1.00",
              "created_at": "1982-10-23 04:57:23",
              "updated_at": "1984-10-26 19:49:01",
              "remove": 0,
              "product_name": "Hardly knowing what she did, she picked up a little now and then raised himself upon tiptoe, put his mouth close to her full size by this time.) 'You're nothing but a pack of cards: the Knave was.",
              "product_link": null,
              "version": "4.0",
              "condition": null,
              "seller_refund_amount": null
            }
          },
          {
            "id": 6,
            "package_id": 80,
            "package_code": "31084720040",
            "box_me_warehouse_tag": "CB_TAG-E707O0P83L2P54O6",
            "order_id": 613,
            "product_id": 3,
            "quantity": 375,
            "weight": 844,
            "change_weight": 2745705.6,
            "dimension_l": 18,
            "dimension_w": 891,
            "dimension_h": 856,
            "stock_in_local": null,
            "stock_out_local": "318905442",
            "at_customer": null,
            "returned": null,
            "lost": null,
            "current_status": "AT_CUSTOMER",
            "shipment_id": 2,
            "created_at": "2018-11-02 19:45:54",
            "updated_at": "1998-07-19 21:27:32",
            "remove": 0,
            "price": null,
            "cod": null,
            "version": "4.0",
            "hold": null,
            "product": {
              "id": 3,
              "order_id": 14,
              "seller_id": 2,
              "portal": "AMAZON_US",
              "sku": "06417de2463f60f2d80cd89dcfb52b4b",
              "parent_sku": "608582f7704e056b0f298e9b32a5697a",
              "link_img": "https://lorempixel.com/640/480/?16049",
              "link_origin": "http://www.chu.vn/eos-et-deleniti-eius-sunt.html",
              "category_id": 4,
              "custom_category_id": 2,
              "price_amount_origin": "2.00",
              "price_amount_local": "47000.00",
              "total_price_amount_local": "94000.00",
              "total_fee_product_local": null,
              "quantity_customer": 2,
              "quantity_purchase": 0,
              "quantity_inspect": 0,
              "price_purchase": null,
              "shipping_fee_purchase": null,
              "tax_fee_purchase": null,
              "variations": "",
              "variation_id": null,
              "note_by_customer": "IS that to be.",
              "total_weight_temporary": "1.00",
              "created_at": "1987-09-10 23:26:22",
              "updated_at": "1995-11-13 21:33:00",
              "remove": 0,
              "product_name": "I've finished.' So they got thrown out to her great delight it fitted! Alice opened the door of the ground--and I should like to be sure; but I can't remember,' said the youth, 'and your jaws are.",
              "product_link": null,
              "version": "4.0",
              "condition": null,
              "seller_refund_amount": null
            }
          },
          {
            "id": 7,
            "package_id": 769,
            "package_code": "54109977825",
            "box_me_warehouse_tag": null,
            "order_id": 303,
            "product_id": 2,
            "quantity": 194,
            "weight": 44,
            "change_weight": 8870728,
            "dimension_l": 430,
            "dimension_w": 482,
            "dimension_h": 214,
            "stock_in_local": "130399573",
            "stock_out_local": "810142959",
            "at_customer": null,
            "returned": "135085178",
            "lost": null,
            "current_status": "RETURNED",
            "shipment_id": 2,
            "created_at": "2008-07-02 01:46:39",
            "updated_at": "1996-12-31 12:30:30",
            "remove": 0,
            "price": null,
            "cod": null,
            "version": "4.0",
            "hold": null,
            "product": {
              "id": 2,
              "order_id": 4,
              "seller_id": 2,
              "portal": "OTHER",
              "sku": "d8bffdabe3f51ce9eb29be84a64344d1",
              "parent_sku": "1737ccf1fd73f72af302ddd49d3d4535",
              "link_img": "https://lorempixel.com/640/480/?11825",
              "link_origin": "http://nhiem.net/qui-maiores-perspiciatis-cumque-qui-illo-libero-alias",
              "category_id": 4,
              "custom_category_id": 3,
              "price_amount_origin": "3.00",
              "price_amount_local": "47000.00",
              "total_price_amount_local": "94000.00",
              "total_fee_product_local": null,
              "quantity_customer": 2,
              "quantity_purchase": 0,
              "quantity_inspect": 0,
              "price_purchase": null,
              "shipping_fee_purchase": null,
              "tax_fee_purchase": null,
              "variations": "",
              "variation_id": null,
              "note_by_customer": "When the Mouse.",
              "total_weight_temporary": "1.00",
              "created_at": "1982-10-23 04:57:23",
              "updated_at": "1984-10-26 19:49:01",
              "remove": 0,
              "product_name": "Hardly knowing what she did, she picked up a little now and then raised himself upon tiptoe, put his mouth close to her full size by this time.) 'You're nothing but a pack of cards: the Knave was.",
              "product_link": null,
              "version": "4.0",
              "condition": null,
              "seller_refund_amount": null
            }
          }
        ]
      },
      {
        "id": 3,
        "shipment_code": "VN2P4K",
        "warehouse_tags": "2GBY19,JC8374,BUGO03,0Z90J5,6ID5VQ,K2G2B2",
        "total_weight": 4396,
        "warehouse_send_id": 50,
        "customer_id": 88,
        "receiver_email": "xdanh@yahoo.com",
        "receiver_name": "Sử Nhã Trà",
        "receiver_phone": "0186 566 6564",
        "receiver_address": "8 Phố Bình Khiêm Hiếu, Xã Nương Tô, Huyện Danh\r\nĐà Nẵng",
        "receiver_country_id": 1,
        "receiver_country_name": "Viet Nam",
        "receiver_province_id": 15,
        "receiver_province_name": "Cần Thơ",
        "receiver_district_id": 39,
        "receiver_district_name": "Đà Nẵng",
        "receiver_post_code": "44535-4846",
        "receiver_address_id": 91,
        "note_by_customer": "White Rabbit as he fumbled over the fire, stirring a large crowd collected round it: there were.",
        "note": "I know. Silence all round, if you hold it too long; and that makes them so often, of course had to kneel down on one side, to look down and looked at her hands, and she was as much as she could, for.",
        "shipment_status": "PICKUP",
        "total_shipping_fee": "600203.00",
        "total_price": "619742.00",
        "total_cod": "464948.00",
        "total_quantity": 775790,
        "is_hold": 0,
        "is_insurance": 0,
        "courier_code": 0,
        "courier_logo": "https://lorempixel.com/150/150/?",
        "courier_estimate_time": "842745249",
        "list_old_shipment_code": "G2501G",
        "created_at": "1979-05-23 10:57:50",
        "updated_at": "1998-08-21 05:06:54",
        "version": "4.0",
        "customer": null,
        "warehouseSend": null,
        "packageItems": [
          {
            "id": 8,
            "package_id": 795,
            "package_code": "16314513937",
            "box_me_warehouse_tag": null,
            "order_id": 677,
            "product_id": 98685989,
            "quantity": 556,
            "weight": 779,
            "change_weight": 980344,
            "dimension_l": 335,
            "dimension_w": 124,
            "dimension_h": 118,
            "stock_in_local": "180810086",
            "stock_out_local": null,
            "at_customer": null,
            "returned": "588690665",
            "lost": null,
            "current_status": "LOST",
            "shipment_id": 3,
            "created_at": "1986-02-10 05:37:44",
            "updated_at": "2011-07-20 20:54:16",
            "remove": 0,
            "price": null,
            "cod": null,
            "version": "4.0",
            "hold": null,
            "product": null
          },
          {
            "id": 9,
            "package_id": 525,
            "package_code": "45470916483",
            "box_me_warehouse_tag": null,
            "order_id": 363,
            "product_id": 4,
            "quantity": 766,
            "weight": 805,
            "change_weight": 351159.6,
            "dimension_l": 407,
            "dimension_w": 6,
            "dimension_h": 719,
            "stock_in_local": null,
            "stock_out_local": null,
            "at_customer": null,
            "returned": null,
            "lost": null,
            "current_status": "STOCK_IN_LOCAL",
            "shipment_id": 3,
            "created_at": "1970-01-11 12:16:37",
            "updated_at": "2015-06-12 06:54:29",
            "remove": 0,
            "price": null,
            "cod": null,
            "version": "4.0",
            "hold": null,
            "product": {
              "id": 4,
              "order_id": 1,
              "seller_id": 2,
              "portal": "AMAZON_US",
              "sku": "2c15b8a5f773fe8d74b6b62980f839f1",
              "parent_sku": "ce9333e4da4b4e32200c54c7989d45eb",
              "link_img": "https://lorempixel.com/640/480/?44436",
              "link_origin": "http://hy.net.vn/dolorem-expedita-quaerat-enim-occaecati-natus-facilis",
              "category_id": 4,
              "custom_category_id": 2,
              "price_amount_origin": "2.00",
              "price_amount_local": "47000.00",
              "total_price_amount_local": "141000.00",
              "total_fee_product_local": null,
              "quantity_customer": 2,
              "quantity_purchase": 0,
              "quantity_inspect": 0,
              "price_purchase": null,
              "shipping_fee_purchase": null,
              "tax_fee_purchase": null,
              "variations": "",
              "variation_id": null,
              "note_by_customer": "THIS!' (Sounds of.",
              "total_weight_temporary": "1.50",
              "created_at": "1974-07-31 22:59:20",
              "updated_at": "1990-11-15 16:54:54",
              "remove": 0,
              "product_name": "Caterpillar sternly. 'Explain yourself!' 'I can't help it,' she thought, 'and hand round the table, but there were a Duck and a bright brass plate with the bread-knife.' The March Hare moved into.",
              "product_link": null,
              "version": "4.0",
              "condition": null,
              "seller_refund_amount": null
            }
          },
          {
            "id": 10,
            "package_id": 83,
            "package_code": "20427003378",
            "box_me_warehouse_tag": null,
            "order_id": 978,
            "product_id": 4,
            "quantity": 713,
            "weight": 363,
            "change_weight": 1559476.8,
            "dimension_l": 573,
            "dimension_w": 126,
            "dimension_h": 108,
            "stock_in_local": "470231028",
            "stock_out_local": "1294705098",
            "at_customer": "324559708",
            "returned": "347184070",
            "lost": null,
            "current_status": "AT_CUSTOMER",
            "shipment_id": 3,
            "created_at": "1987-12-18 07:35:48",
            "updated_at": "2005-12-13 09:53:32",
            "remove": 0,
            "price": null,
            "cod": null,
            "version": "4.0",
            "hold": null,
            "product": {
              "id": 4,
              "order_id": 1,
              "seller_id": 2,
              "portal": "AMAZON_US",
              "sku": "2c15b8a5f773fe8d74b6b62980f839f1",
              "parent_sku": "ce9333e4da4b4e32200c54c7989d45eb",
              "link_img": "https://lorempixel.com/640/480/?44436",
              "link_origin": "http://hy.net.vn/dolorem-expedita-quaerat-enim-occaecati-natus-facilis",
              "category_id": 4,
              "custom_category_id": 2,
              "price_amount_origin": "2.00",
              "price_amount_local": "47000.00",
              "total_price_amount_local": "141000.00",
              "total_fee_product_local": null,
              "quantity_customer": 2,
              "quantity_purchase": 0,
              "quantity_inspect": 0,
              "price_purchase": null,
              "shipping_fee_purchase": null,
              "tax_fee_purchase": null,
              "variations": "",
              "variation_id": null,
              "note_by_customer": "THIS!' (Sounds of.",
              "total_weight_temporary": "1.50",
              "created_at": "1974-07-31 22:59:20",
              "updated_at": "1990-11-15 16:54:54",
              "remove": 0,
              "product_name": "Caterpillar sternly. 'Explain yourself!' 'I can't help it,' she thought, 'and hand round the table, but there were a Duck and a bright brass plate with the bread-knife.' The March Hare moved into.",
              "product_link": null,
              "version": "4.0",
              "condition": null,
              "seller_refund_amount": null
            }
          },
          {
            "id": 11,
            "package_id": 875,
            "package_code": "11760279478",
            "box_me_warehouse_tag": "CB_TAG-7X8V6796K5734U8G",
            "order_id": 785,
            "product_id": 4,
            "quantity": 858,
            "weight": 727,
            "change_weight": 13180464,
            "dimension_l": 424,
            "dimension_w": 495,
            "dimension_h": 314,
            "stock_in_local": null,
            "stock_out_local": "417885922",
            "at_customer": "542886531",
            "returned": null,
            "lost": null,
            "current_status": "RETURNED",
            "shipment_id": 3,
            "created_at": "2010-08-31 00:42:52",
            "updated_at": "1979-10-14 16:56:14",
            "remove": 0,
            "price": null,
            "cod": null,
            "version": "4.0",
            "hold": null,
            "product": {
              "id": 4,
              "order_id": 1,
              "seller_id": 2,
              "portal": "AMAZON_US",
              "sku": "2c15b8a5f773fe8d74b6b62980f839f1",
              "parent_sku": "ce9333e4da4b4e32200c54c7989d45eb",
              "link_img": "https://lorempixel.com/640/480/?44436",
              "link_origin": "http://hy.net.vn/dolorem-expedita-quaerat-enim-occaecati-natus-facilis",
              "category_id": 4,
              "custom_category_id": 2,
              "price_amount_origin": "2.00",
              "price_amount_local": "47000.00",
              "total_price_amount_local": "141000.00",
              "total_fee_product_local": null,
              "quantity_customer": 2,
              "quantity_purchase": 0,
              "quantity_inspect": 0,
              "price_purchase": null,
              "shipping_fee_purchase": null,
              "tax_fee_purchase": null,
              "variations": "",
              "variation_id": null,
              "note_by_customer": "THIS!' (Sounds of.",
              "total_weight_temporary": "1.50",
              "created_at": "1974-07-31 22:59:20",
              "updated_at": "1990-11-15 16:54:54",
              "remove": 0,
              "product_name": "Caterpillar sternly. 'Explain yourself!' 'I can't help it,' she thought, 'and hand round the table, but there were a Duck and a bright brass plate with the bread-knife.' The March Hare moved into.",
              "product_link": null,
              "version": "4.0",
              "condition": null,
              "seller_refund_amount": null
            }
          }
        ]
      },
      {
        "id": 4,
        "shipment_code": "S00HW3",
        "warehouse_tags": "6GX85G,5286H8,089F7T,YYSQ1T",
        "total_weight": 52795,
        "warehouse_send_id": 41,
        "customer_id": 84,
        "receiver_email": "quan.ha@gmail.com",
        "receiver_name": "Từ Đức",
        "receiver_phone": "(033) 583 9700",
        "receiver_address": "2564 Phố Hiên, Phường 34, Quận Đạt Khúc\r\nĐiện Biên",
        "receiver_country_id": 1,
        "receiver_country_name": "Viet Nam",
        "receiver_province_id": 3,
        "receiver_province_name": "Hồ Chí Minh",
        "receiver_district_id": 84,
        "receiver_district_name": "Hải Phòng",
        "receiver_post_code": "06882",
        "receiver_address_id": 1,
        "note_by_customer": "Alice in a very respectful tone, but frowning and making quite a new idea to Alice, and her face.",
        "note": "Alice felt so desperate that she began nibbling at the stick, and tumbled head over heels in its hurry to change the subject of conversation. While she was now about a thousand times as large as.",
        "shipment_status": "RETURN",
        "total_shipping_fee": "993343.00",
        "total_price": "943909.00",
        "total_cod": "274185.00",
        "total_quantity": 387301,
        "is_hold": 0,
        "is_insurance": 0,
        "courier_code": 0,
        "courier_logo": "https://lorempixel.com/150/150/?",
        "courier_estimate_time": "1531586714",
        "list_old_shipment_code": null,
        "created_at": "1980-11-29 03:50:22",
        "updated_at": "2018-07-25 01:37:20",
        "version": "4.0",
        "customer": null,
        "warehouseSend": null,
        "packageItems": []
      },
      {
        "id": 5,
        "shipment_code": "42TI3G",
        "warehouse_tags": "7M3H73,F1VZL8,719A36,P31P52",
        "total_weight": 71218,
        "warehouse_send_id": 92,
        "customer_id": 84,
        "receiver_email": "khoa.ly@hoang.health.vn",
        "receiver_name": "Cô. Quách Bích Thuận",
        "receiver_phone": "0186 182 6089",
        "receiver_address": "2, Ấp Dương, Phường Tăng Vượng Thoa, Huyện 44\r\nLào Cai",
        "receiver_country_id": 1,
        "receiver_country_name": "Viet Nam",
        "receiver_province_id": 41,
        "receiver_province_name": "Hải Phòng",
        "receiver_district_id": 92,
        "receiver_district_name": "Đà Nẵng",
        "receiver_post_code": "369997",
        "receiver_address_id": 35,
        "note_by_customer": "Alice in a large one, but it had fallen into the court, arm-in-arm with the birds hurried off to.",
        "note": "ME.' 'You!' said the March Hare, 'that \"I like what I was a sound of many footsteps, and Alice could think of nothing better to say but 'It belongs to a mouse: she had looked under it, and burning.",
        "shipment_status": "PICKUP",
        "total_shipping_fee": "91350.00",
        "total_price": "296045.00",
        "total_cod": "563658.00",
        "total_quantity": 155537,
        "is_hold": 1,
        "is_insurance": 0,
        "courier_code": 0,
        "courier_logo": "https://lorempixel.com/150/150/?",
        "courier_estimate_time": "144233931",
        "list_old_shipment_code": null,
        "created_at": "1999-06-21 04:14:58",
        "updated_at": "1988-05-10 22:42:22",
        "version": "4.0",
        "customer": null,
        "warehouseSend": null,
        "packageItems": []
      },
      {
        "id": 6,
        "shipment_code": "2VU671",
        "warehouse_tags": "02SYK9,8XD4IO,98Z1V9,945SKC,Q5XZ60,WE89B8,UY1312",
        "total_weight": 26511,
        "warehouse_send_id": 81,
        "customer_id": 60,
        "receiver_email": "mien78@dng.com",
        "receiver_name": "Nông Duy Nhi",
        "receiver_phone": "(84)(94)393-7934",
        "receiver_address": "076 Phố Chế Thiên Ân, Xã Hải, Quận Tôn\r\nKon Tum",
        "receiver_country_id": 1,
        "receiver_country_name": "Viet Nam",
        "receiver_province_id": 1,
        "receiver_province_name": "Đà Nẵng",
        "receiver_district_id": 6,
        "receiver_district_name": "Hồ Chí Minh",
        "receiver_post_code": "68380",
        "receiver_address_id": 35,
        "note_by_customer": "It was high time to wash the things I used to it as far as they were trying to touch her. 'Poor.",
        "note": "The hedgehog was engaged in a confused way, 'Prizes! Prizes!' Alice had never heard of one,' said Alice. 'I wonder what you're talking about,' said Alice. 'Why, you don't even know what to do.",
        "shipment_status": "RETURN",
        "total_shipping_fee": "658294.00",
        "total_price": "872450.00",
        "total_cod": "384221.00",
        "total_quantity": 430851,
        "is_hold": 1,
        "is_insurance": 0,
        "courier_code": 0,
        "courier_logo": "https://lorempixel.com/150/150/?",
        "courier_estimate_time": "1025052559",
        "list_old_shipment_code": "B074J6",
        "created_at": "1974-03-17 15:23:15",
        "updated_at": "2007-02-04 10:55:45",
        "version": "4.0",
        "customer": null,
        "warehouseSend": null,
        "packageItems": []
      },
      {
        "id": 7,
        "shipment_code": "VLP80E",
        "warehouse_tags": "8TXZCN,YSUJE5,G98W53,4W9L5M,ME29CU,311FIM,61BCU9",
        "total_weight": 40716,
        "warehouse_send_id": 27,
        "customer_id": 35,
        "receiver_email": "l.hoa@yahoo.com",
        "receiver_name": "Bác. Châu Vinh",
        "receiver_phone": "(84)(70)696-3475",
        "receiver_address": "9 Phố Diễm, Xã Lễ, Huyện Phương\r\nBắc Ninh",
        "receiver_country_id": 1,
        "receiver_country_name": "Viet Nam",
        "receiver_province_id": 17,
        "receiver_province_name": "Hồ Chí Minh",
        "receiver_district_id": 46,
        "receiver_district_name": "Hồ Chí Minh",
        "receiver_post_code": "34104-6168",
        "receiver_address_id": 45,
        "note_by_customer": "I know!' exclaimed Alice, who was peeping anxiously into her face. 'Wake up, Alice dear!' said her.",
        "note": "So she tucked it away under her arm, with its arms and frowning at the beginning,' the King said, turning to the cur, \"Such a trial, dear Sir, With no jury or judge, would be four thousand miles.",
        "shipment_status": "NEW",
        "total_shipping_fee": "650815.00",
        "total_price": "352912.00",
        "total_cod": "416938.00",
        "total_quantity": 643333,
        "is_hold": 1,
        "is_insurance": 0,
        "courier_code": 0,
        "courier_logo": "https://lorempixel.com/150/150/?",
        "courier_estimate_time": "1296717899",
        "list_old_shipment_code": "P3MI64",
        "created_at": "2009-06-24 22:24:50",
        "updated_at": "2013-01-13 17:22:07",
        "version": "4.0",
        "customer": null,
        "warehouseSend": null,
        "packageItems": []
      },
      {
        "id": 8,
        "shipment_code": "J4HH6H",
        "warehouse_tags": "9VDE2R,CMSNAS",
        "total_weight": 51241,
        "warehouse_send_id": 87,
        "customer_id": 94,
        "receiver_email": "chuong.ngan@gmail.com",
        "receiver_name": "Ung Diệp",
        "receiver_phone": "(84)(77)025-6950",
        "receiver_address": "5 Phố Ong, Xã Tâm, Huyện Kim Sáng\r\nĐắk Lắk",
        "receiver_country_id": 1,
        "receiver_country_name": "Viet Nam",
        "receiver_province_id": 38,
        "receiver_province_name": "Đà Nẵng",
        "receiver_district_id": 99,
        "receiver_district_name": "Hà Nội",
        "receiver_post_code": "77355-6459",
        "receiver_address_id": 68,
        "note_by_customer": "Alice: he had never seen such a rule at processions; 'and besides, what would happen next. The.",
        "note": "Please, Ma'am, is this New Zealand or Australia?' (and she tried the roots of trees, and I've tried hedges,' the Pigeon in a whisper.) 'That would be the right height to be.' 'It is wrong from.",
        "shipment_status": "NEW",
        "total_shipping_fee": "691534.00",
        "total_price": "336584.00",
        "total_cod": "158823.00",
        "total_quantity": 835862,
        "is_hold": 0,
        "is_insurance": 0,
        "courier_code": 0,
        "courier_logo": "https://lorempixel.com/150/150/?",
        "courier_estimate_time": "1191533287",
        "list_old_shipment_code": null,
        "created_at": "1994-02-24 00:21:28",
        "updated_at": "1993-04-07 17:17:31",
        "version": "4.0",
        "customer": null,
        "warehouseSend": null,
        "packageItems": []
      },
      {
        "id": 9,
        "shipment_code": "Y55205",
        "warehouse_tags": "ALUK3L,NC7Q5K,8T0008,KM910X,8N9909,JAV8I1,8G2ZHT",
        "total_weight": 28665,
        "warehouse_send_id": 79,
        "customer_id": 60,
        "receiver_email": "mhy@yahoo.com",
        "receiver_name": "Thập Đôn",
        "receiver_phone": "020 336 1556",
        "receiver_address": "5453, Thôn Hán Chiến Đan, Xã 6, Huyện Đôn Trầm Thục\r\nSóc Trăng",
        "receiver_country_id": 1,
        "receiver_country_name": "Viet Nam",
        "receiver_province_id": 63,
        "receiver_province_name": "Hà Nội",
        "receiver_district_id": 17,
        "receiver_district_name": "Hồ Chí Minh",
        "receiver_post_code": "980594",
        "receiver_address_id": 90,
        "note_by_customer": "CHAPTER II. The Pool of Tears 'Curiouser and curiouser!' cried Alice (she was obliged to write.",
        "note": "YOU with us!\"' 'They were learning to draw, you know--' 'But, it goes on \"THEY ALL RETURNED FROM HIM TO YOU,\"' said Alice. 'Exactly so,' said Alice. 'I'm glad I've seen that done,' thought Alice.",
        "shipment_status": "NEW",
        "total_shipping_fee": "796829.00",
        "total_price": "554235.00",
        "total_cod": "253005.00",
        "total_quantity": 864183,
        "is_hold": 1,
        "is_insurance": 0,
        "courier_code": 0,
        "courier_logo": "https://lorempixel.com/150/150/?",
        "courier_estimate_time": "1354018376",
        "list_old_shipment_code": null,
        "created_at": "2009-09-16 04:02:03",
        "updated_at": "1989-10-05 23:21:13",
        "version": "4.0",
        "customer": null,
        "warehouseSend": null,
        "packageItems": []
      },
      {
        "id": 10,
        "shipment_code": "41W2R0",
        "warehouse_tags": "7KT4E1,97G664,72RT4N,3YZPKC,3LJS7X",
        "total_weight": 30554,
        "warehouse_send_id": 35,
        "customer_id": 72,
        "receiver_email": "idiem@gmail.com",
        "receiver_name": "Cụ. Phạm Khoa",
        "receiver_phone": "84-165-575-0035",
        "receiver_address": "05, Thôn Sử Điền Thương, Phường 84, Quận 3\r\nPhú Thọ",
        "receiver_country_id": 1,
        "receiver_country_name": "Viet Nam",
        "receiver_province_id": 58,
        "receiver_province_name": "Hồ Chí Minh",
        "receiver_district_id": 79,
        "receiver_district_name": "Cần Thơ",
        "receiver_post_code": "884885",
        "receiver_address_id": 59,
        "note_by_customer": "Dormouse, who seemed to listen, the whole court was a sound of a water-well,' said the Queen, who.",
        "note": "March Hare moved into the sky all the things between whiles.' 'Then you may nurse it a minute or two she walked sadly down the chimney?--Nay, I shan't! YOU do it!--That I won't, then!--Bill's to go.",
        "shipment_status": "PICKUP",
        "total_shipping_fee": "565146.00",
        "total_price": "610362.00",
        "total_cod": "305649.00",
        "total_quantity": 366729,
        "is_hold": 0,
        "is_insurance": 0,
        "courier_code": 0,
        "courier_logo": "https://lorempixel.com/150/150/?",
        "courier_estimate_time": "592948655",
        "list_old_shipment_code": null,
        "created_at": "2002-05-20 10:16:35",
        "updated_at": "1987-07-18 16:57:12",
        "version": "4.0",
        "customer": null,
        "warehouseSend": null,
        "packageItems": []
      },
      {
        "id": 11,
        "shipment_code": "IQH6GE",
        "warehouse_tags": "4N75TC,E61WZX,EO63C3,IUE6UL",
        "total_weight": 43743,
        "warehouse_send_id": 49,
        "customer_id": 42,
        "receiver_email": "hien06@han.vn",
        "receiver_name": "Thân Đông Thư",
        "receiver_phone": "84-218-569-3219",
        "receiver_address": "5905 Phố Thạc, Xã Phạm, Quận Minh\r\nPhú Yên",
        "receiver_country_id": 1,
        "receiver_country_name": "Viet Nam",
        "receiver_province_id": 59,
        "receiver_province_name": "Hồ Chí Minh",
        "receiver_district_id": 22,
        "receiver_district_name": "Đà Nẵng",
        "receiver_post_code": "265185",
        "receiver_address_id": 47,
        "note_by_customer": "Longitude I've got to the door, she walked off, leaving Alice alone with the Duchess, who seemed.",
        "note": "I mentioned before, And have grown most uncommonly fat; Yet you turned a corner, 'Oh my ears and the other side of the suppressed guinea-pigs, filled the air, and came back again. 'Keep your.",
        "shipment_status": "NEW",
        "total_shipping_fee": "527420.00",
        "total_price": "985144.00",
        "total_cod": "340297.00",
        "total_quantity": 274285,
        "is_hold": 1,
        "is_insurance": 0,
        "courier_code": 0,
        "courier_logo": "https://lorempixel.com/150/150/?",
        "courier_estimate_time": "1211326838",
        "list_old_shipment_code": null,
        "created_at": "1973-05-05 02:06:08",
        "updated_at": "2010-09-03 10:11:37",
        "version": "4.0",
        "customer": null,
        "warehouseSend": null,
        "packageItems": []
      },
      {
        "id": 12,
        "shipment_code": "HTF10I",
        "warehouse_tags": "5219FT,K0S1MO",
        "total_weight": 39164,
        "warehouse_send_id": 69,
        "customer_id": 1,
        "receiver_email": "liu.bao@khuu.int.vn",
        "receiver_name": "Ông. Phương Hồng",
        "receiver_phone": "(84)(27)936-4852",
        "receiver_address": "381 Phố Lư, Xã 57, Quận Hậu Khánh\r\nBắc Kạn",
        "receiver_country_id": 1,
        "receiver_country_name": "Viet Nam",
        "receiver_province_id": 45,
        "receiver_province_name": "Hồ Chí Minh",
        "receiver_district_id": 19,
        "receiver_district_name": "Hồ Chí Minh",
        "receiver_post_code": "05749",
        "receiver_address_id": 60,
        "note_by_customer": "HE taught us Drawling, Stretching, and Fainting in Coils.' 'What was THAT like?' said Alice. 'Oh.",
        "note": "Alice led the way, was the White Rabbit; 'in fact, there's nothing written on the song, perhaps?' 'I've heard something splashing about in the last word with such sudden violence that Alice quite.",
        "shipment_status": "SENT",
        "total_shipping_fee": "102181.00",
        "total_price": "124781.00",
        "total_cod": "155771.00",
        "total_quantity": 697963,
        "is_hold": 0,
        "is_insurance": 0,
        "courier_code": 0,
        "courier_logo": "https://lorempixel.com/150/150/?",
        "courier_estimate_time": "681743502",
        "list_old_shipment_code": "6KMRSM",
        "created_at": "2012-05-16 02:08:05",
        "updated_at": "2010-06-13 04:48:54",
        "version": "4.0",
        "customer": {
          "id": 1,
          "first_name": "Thương",
          "last_name": "Kiều",
          "email": "ma.lam@gmail.com",
          "phone": "0240-719-9672",
          "username": "tu53",
          "password_hash": "$2y$13$zjKMZ21TN9oICYtiURjaku4xCekmE4apmakhOpzhdQJ6q0L/QeGWe",
          "gender": 0,
          "birthday": "1980-09-24 00:00:00",
          "avatar": "https://lorempixel.com/640/480/?27197",
          "link_verify": "https://bang.biz.vn/praesentium-est-nihil-error-sed-quas-hic-vitae-minus.html",
          "email_verified": 1,
          "phone_verified": 0,
          "last_order_time": "1984-03-31 09:11:48",
          "note_by_employee": "Queen, 'Really, my dear, and that is rather a handsome pig, I think.' And she began again. 'I should have croqueted the Queen's absence, and were resting in the sun. (IF you don't know of any one.",
          "type_customer": 2,
          "access_token": "HOKvHiskzuWMmo2vtjqF7SyLQn64ZXJq",
          "auth_client": "ngx5KpIJR6odS4IdSAWbeD1Zdn_OKLjW",
          "verify_token": "PH5FO77GLB9r8uQ4bSHX52bIb6jfrMd4",
          "reset_password_token": "4sb63ffjvL1f0DE4IO5ZqMiGVOJp7Vhz",
          "store_id": 1,
          "active_shipping": 0,
          "total_xu": "0.0",
          "total_xu_start_date": null,
          "total_xu_expired_date": null,
          "usable_xu": "0.00",
          "usable_xu_start_date": null,
          "usable_xu_expired_date": null,
          "last_use_xu": "0.00",
          "last_use_time": null,
          "last_revenue_xu": "0.00",
          "last_revenue_time": null,
          "verify_code": "Sit.",
          "verify_code_expired_at": "41397471",
          "verify_code_count": 1,
          "verify_code_type": "",
          "created_at": "1476365894",
          "updated_at": "166593298",
          "active": 0,
          "remove": 1,
          "version": "4.0"
        },
        "warehouseSend": null,
        "packageItems": []
      }
    ],
    "_links": {
      "self": {
        "href": "http://weshop-4.0.api.vn/v1/s?page=1"
      },
      "next": {
        "href": "http://weshop-4.0.api.vn/v1/s?page=2"
      },
      "last": {
        "href": "http://weshop-4.0.api.vn/v1/s?page=2"
      }
    },
    "_meta": {
      "totalCount": 28,
      "pageCount": 2,
      "currentPage": 1,
      "perPage": 20
    }
  }
};
