export const TRACKINGS = {
    "success": true,
    "message": "Ok",
    "data": {
        "_items": [
            {
                "id": 1,
                "store_id": 1,
                "package_id": 2,
                "package_code": 0,
                "package_item_id": null,
                "tracking_code": "CFCD208495D565E",
                "order_ids": null,
                "weshop_tag": "WSCFCD208495D56",
                "warehouse_alias": "BMVN_HCM",
                "warehouse_tag": "CBTAG_CFCD20849",
                "warehouse_note": "0",
                "warehouse_status": "open",
                "weight": "99",
                "quantity": "40",
                "dimension_width": "99",
                "dimension_length": "99",
                "dimension_height": "99",
                "operation_note": "Alice, 'we learned French and music.' 'And washing?' said the Dormouse. 'Fourteenth of March, I.",
                "status": "NEW",
                "remove": 0,
                "created_at": "1979-12-17 10:47:35",
                "updated_at": "2014-02-21 11:24:47"
            },
            {
                "id": 2,
                "store_id": 1,
                "package_id": 3,
                "package_code": 0,
                "package_item_id": null,
                "tracking_code": "C4CA4238A0B9238",
                "order_ids": null,
                "weshop_tag": "WSC4CA4238A0B92",
                "warehouse_alias": "WS_HN",
                "warehouse_tag": "CBTAG_C4CA4238A",
                "warehouse_note": "0",
                "warehouse_status": "close",
                "weight": "99",
                "quantity": "93",
                "dimension_width": "99",
                "dimension_length": "99",
                "dimension_height": "99",
                "operation_note": "King said to herself. 'Shy, they seem to be\"--or if you'd like it put the Dormouse went on, 'you.",
                "status": "NEW",
                "remove": 0,
                "created_at": "1976-05-13 02:32:06",
                "updated_at": "1986-10-11 15:46:41"
            },
            {
                "id": 3,
                "store_id": 1,
                "package_id": 1,
                "package_code": 0,
                "package_item_id": null,
                "tracking_code": "C81E728D9D4C2F6",
                "order_ids": null,
                "weshop_tag": "WSC81E728D9D4C2",
                "warehouse_alias": "BMVN_HCM",
                "warehouse_tag": "CBTAG_C81E728D9",
                "warehouse_note": "0",
                "warehouse_status": "open",
                "weight": "99",
                "quantity": "66",
                "dimension_width": "99",
                "dimension_length": "99",
                "dimension_height": "99",
                "operation_note": "Pray, what is the same as the White Rabbit returning, splendidly dressed, with a sigh: 'it's.",
                "status": "NEW",
                "remove": 0,
                "created_at": "1970-03-23 18:41:57",
                "updated_at": "2010-08-18 05:06:29"
            },
            {
                "id": 4,
                "store_id": 1,
                "package_id": 1,
                "package_code": 0,
                "package_item_id": null,
                "tracking_code": "ECCBC87E4B5CE2F",
                "order_ids": null,
                "weshop_tag": "WSECCBC87E4B5CE",
                "warehouse_alias": "BMVN_HN",
                "warehouse_tag": "CBTAG_ECCBC87E4",
                "warehouse_note": "0",
                "warehouse_status": "open",
                "weight": "99",
                "quantity": "7",
                "dimension_width": "99",
                "dimension_length": "99",
                "dimension_height": "99",
                "operation_note": "Alice; 'only, as it's asleep, I suppose Dinah'll be sending me on messages next!' And she began.",
                "status": "NEW",
                "remove": 0,
                "created_at": "2011-08-17 18:21:32",
                "updated_at": "2001-10-25 04:52:28"
            },
            {
                "id": 5,
                "store_id": 1,
                "package_id": 1,
                "package_code": 0,
                "package_item_id": null,
                "tracking_code": "A87FF679A2F3E71",
                "order_ids": null,
                "weshop_tag": "WSA87FF679A2F3E",
                "warehouse_alias": "BMVN_HCM",
                "warehouse_tag": "CBTAG_A87FF679A",
                "warehouse_note": "0",
                "warehouse_status": "open",
                "weight": "99",
                "quantity": "57",
                "dimension_width": "99",
                "dimension_length": "99",
                "dimension_height": "99",
                "operation_note": "Pigeon had finished. 'As if it had been, it suddenly appeared again. 'By-the-bye, what became of.",
                "status": "NEW",
                "remove": 0,
                "created_at": "1980-09-26 13:54:39",
                "updated_at": "1998-09-16 19:27:00"
            },
            {
                "id": 6,
                "store_id": 1,
                "package_id": 3,
                "package_code": 0,
                "package_item_id": null,
                "tracking_code": "E4DA3B7FBBCE234",
                "order_ids": null,
                "weshop_tag": "WSE4DA3B7FBBCE2",
                "warehouse_alias": "BMVN_HCM",
                "warehouse_tag": "CBTAG_E4DA3B7FB",
                "warehouse_note": "0",
                "warehouse_status": "open",
                "weight": "99",
                "quantity": "66",
                "dimension_width": "99",
                "dimension_length": "99",
                "dimension_height": "99",
                "operation_note": "A secret, kept from all the other end of the Gryphon, and the words 'EAT ME' were beautifully.",
                "status": "NEW",
                "remove": 0,
                "created_at": "1992-12-01 14:40:39",
                "updated_at": "1972-09-01 03:01:19"
            },
            {
                "id": 7,
                "store_id": 1,
                "package_id": 3,
                "package_code": 0,
                "package_item_id": null,
                "tracking_code": "1679091C5A880FA",
                "order_ids": null,
                "weshop_tag": "WS1679091C5A880",
                "warehouse_alias": "BMVN_HCM",
                "warehouse_tag": "CBTAG_1679091C5",
                "warehouse_note": "0",
                "warehouse_status": "close",
                "weight": "99",
                "quantity": "21",
                "dimension_width": "99",
                "dimension_length": "99",
                "dimension_height": "99",
                "operation_note": "The poor little thing was to twist it up into the book her sister on the OUTSIDE.' He unfolded the.",
                "status": "NEW",
                "remove": 0,
                "created_at": "2018-05-31 04:59:59",
                "updated_at": "1995-06-23 07:35:42"
            },
            {
                "id": 8,
                "store_id": 1,
                "package_id": 2,
                "package_code": 0,
                "package_item_id": null,
                "tracking_code": "8F14E45FCEEA167",
                "order_ids": null,
                "weshop_tag": "WS8F14E45FCEEA1",
                "warehouse_alias": "BMVN_HCM",
                "warehouse_tag": "CBTAG_8F14E45FC",
                "warehouse_note": "0",
                "warehouse_status": null,
                "weight": "99",
                "quantity": "12",
                "dimension_width": "99",
                "dimension_length": "99",
                "dimension_height": "99",
                "operation_note": "But her sister on the slate. 'Herald, read the accusation!' said the Hatter. 'Nor I,' said the.",
                "status": "NEW",
                "remove": 0,
                "created_at": "2018-01-20 08:16:46",
                "updated_at": "1985-10-31 17:08:57"
            },
            {
                "id": 9,
                "store_id": 1,
                "package_id": 2,
                "package_code": 0,
                "package_item_id": null,
                "tracking_code": "C9F0F895FB98AB9",
                "order_ids": null,
                "weshop_tag": "WSC9F0F895FB98A",
                "warehouse_alias": "WS_HN",
                "warehouse_tag": "CBTAG_C9F0F895F",
                "warehouse_note": "0",
                "warehouse_status": "close",
                "weight": "99",
                "quantity": "18",
                "dimension_width": "99",
                "dimension_length": "99",
                "dimension_height": "99",
                "operation_note": "CHORUS. 'Wow! wow! wow!' 'Here! you may stand down,' continued the Gryphon. 'It's all his fancy.",
                "status": "NEW",
                "remove": 0,
                "created_at": "2005-05-08 08:16:31",
                "updated_at": "1974-04-12 00:25:20"
            },
            {
                "id": 10,
                "store_id": 1,
                "package_id": 1,
                "package_code": 0,
                "package_item_id": null,
                "tracking_code": "45C48CCE2E2D7FB",
                "order_ids": null,
                "weshop_tag": "WS45C48CCE2E2D7",
                "warehouse_alias": "BMVN_HN",
                "warehouse_tag": "CBTAG_45C48CCE2",
                "warehouse_note": "0",
                "warehouse_status": "close",
                "weight": "99",
                "quantity": "81",
                "dimension_width": "99",
                "dimension_length": "99",
                "dimension_height": "99",
                "operation_note": "I to get dry again: they had settled down again into its mouth open, gazing up into the sky all.",
                "status": "NEW",
                "remove": 0,
                "created_at": "2013-05-01 23:47:26",
                "updated_at": "2002-10-23 11:11:32"
            },
            {
                "id": 11,
                "store_id": 1,
                "package_id": 1,
                "package_code": 0,
                "package_item_id": null,
                "tracking_code": "D3D9446802A4425",
                "order_ids": null,
                "weshop_tag": "WSD3D9446802A44",
                "warehouse_alias": "BMVN_HCM",
                "warehouse_tag": "CBTAG_D3D944680",
                "warehouse_note": "0",
                "warehouse_status": "close",
                "weight": "99",
                "quantity": "91",
                "dimension_width": "99",
                "dimension_length": "99",
                "dimension_height": "99",
                "operation_note": "ME, and told me you had been looking at them with one eye, How the Owl had the dish as its share.",
                "status": "NEW",
                "remove": 0,
                "created_at": "2009-01-17 06:48:50",
                "updated_at": "1978-09-01 23:21:32"
            },
            {
                "id": 12,
                "store_id": 1,
                "package_id": 3,
                "package_code": 0,
                "package_item_id": null,
                "tracking_code": "6512BD43D9CAA6E",
                "order_ids": null,
                "weshop_tag": "WS6512BD43D9CAA",
                "warehouse_alias": "BMVN_HN",
                "warehouse_tag": "CBTAG_6512BD43D",
                "warehouse_note": "0",
                "warehouse_status": "open",
                "weight": "99",
                "quantity": "13",
                "dimension_width": "99",
                "dimension_length": "99",
                "dimension_height": "99",
                "operation_note": "Five, in a louder tone. 'ARE you to set about it; if I'm not particular as to prevent its undoing.",
                "status": "NEW",
                "remove": 0,
                "created_at": "1975-06-22 13:10:21",
                "updated_at": "2015-09-04 21:34:46"
            },
            {
                "id": 13,
                "store_id": 1,
                "package_id": 1,
                "package_code": 0,
                "package_item_id": null,
                "tracking_code": "C20AD4D76FE9775",
                "order_ids": null,
                "weshop_tag": "WSC20AD4D76FE97",
                "warehouse_alias": "WS_HN",
                "warehouse_tag": "CBTAG_C20AD4D76",
                "warehouse_note": "0",
                "warehouse_status": "close",
                "weight": "99",
                "quantity": "16",
                "dimension_width": "99",
                "dimension_length": "99",
                "dimension_height": "99",
                "operation_note": "Soup! Beau--ootiful Soo--oop! Beau--ootiful Soo--oop! Beau--ootiful Soo--oop! Soo--oop of the.",
                "status": "NEW",
                "remove": 0,
                "created_at": "2010-05-25 04:33:18",
                "updated_at": "2004-07-12 12:06:43"
            },
            {
                "id": 14,
                "store_id": 1,
                "package_id": 1,
                "package_code": 0,
                "package_item_id": null,
                "tracking_code": "C51CE410C124A10",
                "order_ids": null,
                "weshop_tag": "WSC51CE410C124A",
                "warehouse_alias": "WS_HN",
                "warehouse_tag": "CBTAG_C51CE410C",
                "warehouse_note": "0",
                "warehouse_status": "open",
                "weight": "99",
                "quantity": "42",
                "dimension_width": "99",
                "dimension_length": "99",
                "dimension_height": "99",
                "operation_note": "Queen said--' 'Get to your tea; it's getting late.' So Alice got up and walking off to trouble.",
                "status": "NEW",
                "remove": 0,
                "created_at": "1981-09-17 07:07:52",
                "updated_at": "1993-07-03 10:02:48"
            },
            {
                "id": 15,
                "store_id": 1,
                "package_id": 1,
                "package_code": 0,
                "package_item_id": null,
                "tracking_code": "AAB3238922BCC25",
                "order_ids": null,
                "weshop_tag": "WSAAB3238922BCC",
                "warehouse_alias": "WS_HN",
                "warehouse_tag": "CBTAG_AAB323892",
                "warehouse_note": "0",
                "warehouse_status": "open",
                "weight": "99",
                "quantity": "52",
                "dimension_width": "99",
                "dimension_length": "99",
                "dimension_height": "99",
                "operation_note": "He sent them word I had not gone (We know it was not quite like the tone of great dismay, and.",
                "status": "NEW",
                "remove": 0,
                "created_at": "1982-01-20 02:46:20",
                "updated_at": "2010-03-06 17:16:13"
            },
            {
                "id": 16,
                "store_id": 1,
                "package_id": 2,
                "package_code": 0,
                "package_item_id": null,
                "tracking_code": "9BF31C7FF062936",
                "order_ids": null,
                "weshop_tag": "WS9BF31C7FF0629",
                "warehouse_alias": "WS_HN",
                "warehouse_tag": "CBTAG_9BF31C7FF",
                "warehouse_note": "0",
                "warehouse_status": "open",
                "weight": "99",
                "quantity": "91",
                "dimension_width": "99",
                "dimension_length": "99",
                "dimension_height": "99",
                "operation_note": "I only wish they WOULD put their heads down! I am now? That'll be a walrus or hippopotamus, but.",
                "status": "NEW",
                "remove": 0,
                "created_at": "2002-05-02 19:36:09",
                "updated_at": "1990-07-08 15:39:44"
            },
            {
                "id": 17,
                "store_id": 1,
                "package_id": 2,
                "package_code": 0,
                "package_item_id": null,
                "tracking_code": "C74D97B01EAE257",
                "order_ids": null,
                "weshop_tag": "WSC74D97B01EAE2",
                "warehouse_alias": "WS_HN",
                "warehouse_tag": "CBTAG_C74D97B01",
                "warehouse_note": "0",
                "warehouse_status": null,
                "weight": "99",
                "quantity": "62",
                "dimension_width": "99",
                "dimension_length": "99",
                "dimension_height": "99",
                "operation_note": "Footman's head: it just now.' 'It's the first figure,' said the Caterpillar. Alice thought to.",
                "status": "NEW",
                "remove": 0,
                "created_at": "1974-12-26 00:03:30",
                "updated_at": "2003-05-28 22:46:02"
            },
            {
                "id": 18,
                "store_id": 1,
                "package_id": 1,
                "package_code": 0,
                "package_item_id": null,
                "tracking_code": "70EFDF2EC9B0860",
                "order_ids": null,
                "weshop_tag": "WS70EFDF2EC9B08",
                "warehouse_alias": "BMVN_HCM",
                "warehouse_tag": "CBTAG_70EFDF2EC",
                "warehouse_note": "0",
                "warehouse_status": "close",
                "weight": "99",
                "quantity": "10",
                "dimension_width": "99",
                "dimension_length": "99",
                "dimension_height": "99",
                "operation_note": "The Hatter was the White Rabbit: it was good manners for her to carry it further. So she stood.",
                "status": "NEW",
                "remove": 0,
                "created_at": "1998-07-13 07:45:54",
                "updated_at": "1988-03-08 05:12:10"
            },
            {
                "id": 19,
                "store_id": 1,
                "package_id": 1,
                "package_code": 0,
                "package_item_id": null,
                "tracking_code": "6F4922F45568161",
                "order_ids": null,
                "weshop_tag": "WS6F4922F455681",
                "warehouse_alias": "BMVN_HN",
                "warehouse_tag": "CBTAG_6F4922F45",
                "warehouse_note": "0",
                "warehouse_status": "close",
                "weight": "99",
                "quantity": "34",
                "dimension_width": "99",
                "dimension_length": "99",
                "dimension_height": "99",
                "operation_note": "OURS they had at the mushroom for a baby: altogether Alice did not appear, and after a pause: 'the.",
                "status": "NEW",
                "remove": 0,
                "created_at": "1987-01-05 23:54:24",
                "updated_at": "1985-06-14 05:48:05"
            },
            {
                "id": 20,
                "store_id": 1,
                "package_id": 2,
                "package_code": 0,
                "package_item_id": null,
                "tracking_code": "1F0E3DAD9990834",
                "order_ids": null,
                "weshop_tag": "WS1F0E3DAD99908",
                "warehouse_alias": "WS_HN",
                "warehouse_tag": "CBTAG_1F0E3DAD9",
                "warehouse_note": "0",
                "warehouse_status": "close",
                "weight": "99",
                "quantity": "35",
                "dimension_width": "99",
                "dimension_length": "99",
                "dimension_height": "99",
                "operation_note": "White Rabbit, 'and that's a fact.' Alice did not get hold of this ointment--one shilling the box.",
                "status": "NEW",
                "remove": 0,
                "created_at": "2010-10-20 22:55:31",
                "updated_at": "1975-06-26 11:17:11"
            }
        ],
        "_links": {
            "self": {
                "href": "http://weshop-4.0.api.vn/v1/tracking-code?p=1"
            },
            "next": {
                "href": "http://weshop-4.0.api.vn/v1/tracking-code?p=2"
            },
            "last": {
                "href": "http://weshop-4.0.api.vn/v1/tracking-code?p=10"
            }
        },
        "_meta": {
            "totalCount": 200,
            "pageCount": 10,
            "currentPage": 1,
            "perPage": 20
        }
    }
};
