export const TRACKINGS = {
    'success': true,
    'message': 'Ok',
    'data': {
        '_items': [
            {
                'id': 1,
                'store_id': 1,
                'manifest_id': 3,
                'manifest_code': 'HNC555',
                'package_id': 3,
                'package_code': 'PB_0000000000',
                'package_item_id': null,
                'tracking_code': 'TKCFCD208495D56',
                'order_ids': null,
                'weshop_tag': 'WSCFCD208495D56',
                'warehouse_alias': 'BMVN_HCM',
                'warehouse_tag': 'CBTAG_CFCD20849',
                'warehouse_note': 'Said the mouse doesn\'t get out." Only I don\'t keep the same height as herself; and when she had.',
                'warehouse_status': 'close',
                'weight': '99',
                'quantity': '56',
                'dimension_width': '99',
                'dimension_length': '99',
                'dimension_height': '99',
                'operation_note': 'YOU, and no room to open them again, and said, very gravely, \'I think, you ought to be a walrus or.',
                'status': 'NEW',
                'remove': 0,
                'created_at': '1988-12-27 22:40:09',
                'updated_at': '1997-08-07 18:04:48',
                'version': '4.0'
            },
            {
                'id': 2,
                'store_id': 1,
                'manifest_id': 2,
                'manifest_code': 'VA1234',
                'package_id': 2,
                'package_code': 'PK_0987654323',
                'package_item_id': null,
                'tracking_code': 'TKC4CA4238A0B92',
                'order_ids': null,
                'weshop_tag': 'WSC4CA4238A0B92',
                'warehouse_alias': 'BMVN_HCM',
                'warehouse_tag': 'CBTAG_C4CA4238A',
                'warehouse_note': 'Alice recognised the White Rabbit, trotting slowly back again, and Alice guessed who it was, and.',
                'warehouse_status': 'close',
                'weight': '99',
                'quantity': '60',
                'dimension_width': '99',
                'dimension_length': '99',
                'dimension_height': '99',
                'operation_note': 'Gryphon, lying fast asleep in the grass, merely remarking as it was getting so thin--and the.',
                'status': 'NEW',
                'remove': 0,
                'created_at': '1977-04-15 08:46:26',
                'updated_at': '1992-11-14 22:39:28',
                'version': '4.0'
            },
            {
                'id': 3,
                'store_id': 1,
                'manifest_id': 1,
                'manifest_code': 'RVS789',
                'package_id': 2,
                'package_code': 'PK_0987654323',
                'package_item_id': null,
                'tracking_code': 'TKC81E728D9D4C2',
                'order_ids': null,
                'weshop_tag': 'WSC81E728D9D4C2',
                'warehouse_alias': 'BMVN_HN',
                'warehouse_tag': 'CBTAG_C81E728D9',
                'warehouse_note': 'Alice, a good deal: this fireplace is narrow, to be no use now,\' thought poor Alice, and her face.',
                'warehouse_status': 'close',
                'weight': '99',
                'quantity': '24',
                'dimension_width': '99',
                'dimension_length': '99',
                'dimension_height': '99',
                'operation_note': 'Alice had no idea how to set them free, Exactly as we were. My notion was that she never knew.',
                'status': 'NEW',
                'remove': 0,
                'created_at': '1993-01-26 06:13:51',
                'updated_at': '2015-01-13 12:58:58',
                'version': '4.0'
            },
            {
                'id': 4,
                'store_id': 1,
                'manifest_id': 3,
                'manifest_code': 'HNC555',
                'package_id': 1,
                'package_code': 'PK_1223454321',
                'package_item_id': null,
                'tracking_code': 'TKECCBC87E4B5CE',
                'order_ids': null,
                'weshop_tag': 'WSECCBC87E4B5CE',
                'warehouse_alias': 'BMVN_HCM',
                'warehouse_tag': 'CBTAG_ECCBC87E4',
                'warehouse_note': 'Rabbit in a louder tone. \'ARE you to get in?\' \'There might be some sense in your knocking,\' the.',
                'warehouse_status': null,
                'weight': '99',
                'quantity': '31',
                'dimension_width': '99',
                'dimension_length': '99',
                'dimension_height': '99',
                'operation_note': 'Poor Alice! It was so much frightened that she was beginning to write with one of the jurors had a.',
                'status': 'NEW',
                'remove': 0,
                'created_at': '2004-02-03 23:45:30',
                'updated_at': '1995-10-06 16:39:34',
                'version': '4.0'
            },
            {
                'id': 5,
                'store_id': 1,
                'manifest_id': 1,
                'manifest_code': 'RVS789',
                'package_id': 1,
                'package_code': 'PK_1223454321',
                'package_item_id': null,
                'tracking_code': 'TKA87FF679A2F3E',
                'order_ids': null,
                'weshop_tag': 'WSA87FF679A2F3E',
                'warehouse_alias': 'BMVN_HN',
                'warehouse_tag': 'CBTAG_A87FF679A',
                'warehouse_note': 'I\'m not particular as to size,\' Alice hastily replied; \'at least--at least I know is, something.',
                'warehouse_status': 'open',
                'weight': '99',
                'quantity': '73',
                'dimension_width': '99',
                'dimension_length': '99',
                'dimension_height': '99',
                'operation_note': 'English!\' said the last few minutes it puffed away without being invited,\' said the Queen, but she.',
                'status': 'NEW',
                'remove': 0,
                'created_at': '1997-04-01 20:00:43',
                'updated_at': '1997-01-08 14:07:20',
                'version': '4.0'
            },
            {
                'id': 6,
                'store_id': 1,
                'manifest_id': 2,
                'manifest_code': 'VA1234',
                'package_id': 1,
                'package_code': 'PK_1223454321',
                'package_item_id': null,
                'tracking_code': 'TKE4DA3B7FBBCE2',
                'order_ids': null,
                'weshop_tag': 'WSE4DA3B7FBBCE2',
                'warehouse_alias': 'WS_HN',
                'warehouse_tag': 'CBTAG_E4DA3B7FB',
                'warehouse_note': 'Caterpillar took the least notice of her little sister\'s dream. The long grass rustled at her.',
                'warehouse_status': 'close',
                'weight': '99',
                'quantity': '35',
                'dimension_width': '99',
                'dimension_length': '99',
                'dimension_height': '99',
                'operation_note': 'I don\'t believe it,\' said the Duchess: \'what a clear way you go,\' said the March Hare moved into.',
                'status': 'NEW',
                'remove': 0,
                'created_at': '1997-03-11 01:22:36',
                'updated_at': '1971-12-16 09:35:38',
                'version': '4.0'
            },
            {
                'id': 7,
                'store_id': 1,
                'manifest_id': 1,
                'manifest_code': 'RVS789',
                'package_id': 2,
                'package_code': 'PK_0987654323',
                'package_item_id': null,
                'tracking_code': 'TK1679091C5A880',
                'order_ids': null,
                'weshop_tag': 'WS1679091C5A880',
                'warehouse_alias': 'BMVN_HCM',
                'warehouse_tag': 'CBTAG_1679091C5',
                'warehouse_note': 'Mouse\'s tail; \'but why do you want to stay with it as far as they were nowhere to be told so.',
                'warehouse_status': 'open',
                'weight': '99',
                'quantity': '95',
                'dimension_width': '99',
                'dimension_length': '99',
                'dimension_height': '99',
                'operation_note': 'Duchess, as she was walking hand in hand, in couples: they were gardeners, or soldiers, or.',
                'status': 'NEW',
                'remove': 0,
                'created_at': '1992-11-11 15:43:28',
                'updated_at': '1989-07-05 06:13:43',
                'version': '4.0'
            },
            {
                'id': 8,
                'store_id': 1,
                'manifest_id': 1,
                'manifest_code': 'RVS789',
                'package_id': 3,
                'package_code': 'PB_0000000000',
                'package_item_id': null,
                'tracking_code': 'TK8F14E45FCEEA1',
                'order_ids': null,
                'weshop_tag': 'WS8F14E45FCEEA1',
                'warehouse_alias': 'BMVN_HCM',
                'warehouse_tag': 'CBTAG_8F14E45FC',
                'warehouse_note': 'The Duchess took no notice of her favourite word \'moral,\' and the Queen furiously, throwing an.',
                'warehouse_status': 'open',
                'weight': '99',
                'quantity': '3',
                'dimension_width': '99',
                'dimension_length': '99',
                'dimension_height': '99',
                'operation_note': 'Bill! I wouldn\'t say anything about it, and very soon had to stop and untwist it. After a while.',
                'status': 'NEW',
                'remove': 0,
                'created_at': '2000-09-21 08:21:21',
                'updated_at': '1987-05-18 08:52:09',
                'version': '4.0'
            },
            {
                'id': 9,
                'store_id': 1,
                'manifest_id': 1,
                'manifest_code': 'RVS789',
                'package_id': 2,
                'package_code': 'PK_0987654323',
                'package_item_id': null,
                'tracking_code': 'TKC9F0F895FB98A',
                'order_ids': null,
                'weshop_tag': 'WSC9F0F895FB98A',
                'warehouse_alias': 'BMVN_HN',
                'warehouse_tag': 'CBTAG_C9F0F895F',
                'warehouse_note': 'Hatter, it woke up again as quickly as she was not otherwise than what you would have made a rush.',
                'warehouse_status': null,
                'weight': '99',
                'quantity': '90',
                'dimension_width': '99',
                'dimension_length': '99',
                'dimension_height': '99',
                'operation_note': 'AND WASHING--extra."\' \'You couldn\'t have done that, you know,\' said the Hatter, and, just as she.',
                'status': 'NEW',
                'remove': 0,
                'created_at': '1976-06-29 23:20:52',
                'updated_at': '1986-05-29 17:02:53',
                'version': '4.0'
            },
            {
                'id': 10,
                'store_id': 1,
                'manifest_id': 1,
                'manifest_code': 'RVS789',
                'package_id': 2,
                'package_code': 'PK_0987654323',
                'package_item_id': null,
                'tracking_code': 'TK45C48CCE2E2D7',
                'order_ids': null,
                'weshop_tag': 'WS45C48CCE2E2D7',
                'warehouse_alias': 'BMVN_HCM',
                'warehouse_tag': 'CBTAG_45C48CCE2',
                'warehouse_note': 'However, the Multiplication Table doesn\'t signify: let\'s try the whole pack of cards, after all. I.',
                'warehouse_status': null,
                'weight': '99',
                'quantity': '43',
                'dimension_width': '99',
                'dimension_length': '99',
                'dimension_height': '99',
                'operation_note': 'Hatter, and here the Mock Turtle in a sulky tone, as it was an old Crab took the watch and looked.',
                'status': 'NEW',
                'remove': 0,
                'created_at': '2004-08-06 15:32:06',
                'updated_at': '2015-05-09 13:03:09',
                'version': '4.0'
            },
            {
                'id': 11,
                'store_id': 1,
                'manifest_id': 1,
                'manifest_code': 'RVS789',
                'package_id': 3,
                'package_code': 'PB_0000000000',
                'package_item_id': null,
                'tracking_code': 'TKD3D9446802A44',
                'order_ids': null,
                'weshop_tag': 'WSD3D9446802A44',
                'warehouse_alias': 'BMVN_HCM',
                'warehouse_tag': 'CBTAG_D3D944680',
                'warehouse_note': 'Rome, and Rome--no, THAT\'S all wrong, I\'m certain! I must be growing small again.\' She got up and.',
                'warehouse_status': null,
                'weight': '99',
                'quantity': '55',
                'dimension_width': '99',
                'dimension_length': '99',
                'dimension_height': '99',
                'operation_note': 'I was, I shouldn\'t like THAT!\' \'Oh, you foolish Alice!\' she answered herself. \'How can you learn.',
                'status': 'NEW',
                'remove': 0,
                'created_at': '1999-06-04 08:19:43',
                'updated_at': '2007-05-02 13:37:34',
                'version': '4.0'
            },
            {
                'id': 12,
                'store_id': 1,
                'manifest_id': 3,
                'manifest_code': 'HNC555',
                'package_id': 2,
                'package_code': 'PK_0987654323',
                'package_item_id': null,
                'tracking_code': 'TK6512BD43D9CAA',
                'order_ids': null,
                'weshop_tag': 'WS6512BD43D9CAA',
                'warehouse_alias': 'WS_HN',
                'warehouse_tag': 'CBTAG_6512BD43D',
                'warehouse_note': 'Hatter: \'I\'m on the trumpet, and called out, \'First witness!\' The first question of course you.',
                'warehouse_status': 'close',
                'weight': '99',
                'quantity': '98',
                'dimension_width': '99',
                'dimension_length': '99',
                'dimension_height': '99',
                'operation_note': 'KNOW IT TO BE TRUE--" that\'s the jury-box,\' thought Alice, \'and if it had grown so large a house.',
                'status': 'NEW',
                'remove': 0,
                'created_at': '2010-09-20 20:28:14',
                'updated_at': '2010-10-19 10:08:41',
                'version': '4.0'
            },
            {
                'id': 13,
                'store_id': 1,
                'manifest_id': 3,
                'manifest_code': 'HNC555',
                'package_id': 2,
                'package_code': 'PK_0987654323',
                'package_item_id': null,
                'tracking_code': 'TKC20AD4D76FE97',
                'order_ids': null,
                'weshop_tag': 'WSC20AD4D76FE97',
                'warehouse_alias': 'WS_HN',
                'warehouse_tag': 'CBTAG_C20AD4D76',
                'warehouse_note': 'Duchess, it had finished this short speech, they all quarrel so dreadfully one can\'t hear oneself.',
                'warehouse_status': null,
                'weight': '99',
                'quantity': '9',
                'dimension_width': '99',
                'dimension_length': '99',
                'dimension_height': '99',
                'operation_note': 'Alice, \'to speak to this mouse? Everything is so out-of-the-way down here, that I should frighten.',
                'status': 'NEW',
                'remove': 0,
                'created_at': '1999-10-17 12:17:08',
                'updated_at': '1999-12-06 06:47:44',
                'version': '4.0'
            },
            {
                'id': 14,
                'store_id': 1,
                'manifest_id': 2,
                'manifest_code': 'VA1234',
                'package_id': 3,
                'package_code': 'PB_0000000000',
                'package_item_id': null,
                'tracking_code': 'TKC51CE410C124A',
                'order_ids': null,
                'weshop_tag': 'WSC51CE410C124A',
                'warehouse_alias': 'BMVN_HCM',
                'warehouse_tag': 'CBTAG_C51CE410C',
                'warehouse_note': 'Alice, very much at this, but at the top with its tongue hanging out of their wits!\' So she tucked.',
                'warehouse_status': 'close',
                'weight': '99',
                'quantity': '34',
                'dimension_width': '99',
                'dimension_length': '99',
                'dimension_height': '99',
                'operation_note': 'I shan\'t go, at any rate: go and take it away!\' There was a dead silence instantly, and Alice.',
                'status': 'NEW',
                'remove': 0,
                'created_at': '2016-11-28 15:57:07',
                'updated_at': '1973-10-09 06:20:33',
                'version': '4.0'
            },
            {
                'id': 15,
                'store_id': 1,
                'manifest_id': 1,
                'manifest_code': 'RVS789',
                'package_id': 2,
                'package_code': 'PK_0987654323',
                'package_item_id': null,
                'tracking_code': 'TKAAB3238922BCC',
                'order_ids': null,
                'weshop_tag': 'WSAAB3238922BCC',
                'warehouse_alias': 'BMVN_HN',
                'warehouse_tag': 'CBTAG_AAB323892',
                'warehouse_note': 'Hatter replied. \'Of course twinkling begins with an anxious look at all a proper way of speaking.',
                'warehouse_status': null,
                'weight': '99',
                'quantity': '68',
                'dimension_width': '99',
                'dimension_length': '99',
                'dimension_height': '99',
                'operation_note': 'Five! Don\'t go splashing paint over me like that!\' \'I couldn\'t afford to learn it.\' said the King.',
                'status': 'NEW',
                'remove': 0,
                'created_at': '1976-12-24 01:34:35',
                'updated_at': '1995-08-26 14:55:43',
                'version': '4.0'
            },
            {
                'id': 16,
                'store_id': 1,
                'manifest_id': 1,
                'manifest_code': 'RVS789',
                'package_id': 2,
                'package_code': 'PK_0987654323',
                'package_item_id': null,
                'tracking_code': 'TK9BF31C7FF0629',
                'order_ids': null,
                'weshop_tag': 'WS9BF31C7FF0629',
                'warehouse_alias': 'WS_HN',
                'warehouse_tag': 'CBTAG_9BF31C7FF',
                'warehouse_note': 'Gryphon. \'Then, you know,\' said Alice, \'but I must have a prize herself, you know,\' said the.',
                'warehouse_status': 'close',
                'weight': '99',
                'quantity': '97',
                'dimension_width': '99',
                'dimension_length': '99',
                'dimension_height': '99',
                'operation_note': 'I got up very carefully, nibbling first at one and then I\'ll tell you my adventures--beginning.',
                'status': 'NEW',
                'remove': 0,
                'created_at': '1973-09-26 14:49:07',
                'updated_at': '1970-07-09 08:39:13',
                'version': '4.0'
            },
            {
                'id': 17,
                'store_id': 1,
                'manifest_id': 1,
                'manifest_code': 'RVS789',
                'package_id': 3,
                'package_code': 'PB_0000000000',
                'package_item_id': null,
                'tracking_code': 'TKC74D97B01EAE2',
                'order_ids': null,
                'weshop_tag': 'WSC74D97B01EAE2',
                'warehouse_alias': 'BMVN_HCM',
                'warehouse_tag': 'CBTAG_C74D97B01',
                'warehouse_note': 'Dormouse, not choosing to notice this last remark that had fallen into it: there was a good.',
                'warehouse_status': null,
                'weight': '99',
                'quantity': '46',
                'dimension_width': '99',
                'dimension_length': '99',
                'dimension_height': '99',
                'operation_note': 'All on a bough of a book,\' thought Alice to herself, \'in my going out altogether, like a serpent.',
                'status': 'NEW',
                'remove': 0,
                'created_at': '1986-03-20 16:40:50',
                'updated_at': '1981-10-13 15:01:33',
                'version': '4.0'
            },
            {
                'id': 18,
                'store_id': 1,
                'manifest_id': 3,
                'manifest_code': 'HNC555',
                'package_id': 2,
                'package_code': 'PK_0987654323',
                'package_item_id': null,
                'tracking_code': 'TK70EFDF2EC9B08',
                'order_ids': null,
                'weshop_tag': 'WS70EFDF2EC9B08',
                'warehouse_alias': 'BMVN_HCM',
                'warehouse_tag': 'CBTAG_70EFDF2EC',
                'warehouse_note': 'I ever heard!\' \'Yes, I think it so quickly that the way out of sight: then it watched the Queen.',
                'warehouse_status': null,
                'weight': '99',
                'quantity': '81',
                'dimension_width': '99',
                'dimension_length': '99',
                'dimension_height': '99',
                'operation_note': 'What happened to you? Tell us all about it!\' and he called the Queen, and Alice was rather glad.',
                'status': 'NEW',
                'remove': 0,
                'created_at': '1987-01-01 09:12:37',
                'updated_at': '1983-09-02 22:51:30',
                'version': '4.0'
            },
            {
                'id': 19,
                'store_id': 1,
                'manifest_id': 3,
                'manifest_code': 'HNC555',
                'package_id': 3,
                'package_code': 'PB_0000000000',
                'package_item_id': null,
                'tracking_code': 'TK6F4922F455681',
                'order_ids': null,
                'weshop_tag': 'WS6F4922F455681',
                'warehouse_alias': 'BMVN_HN',
                'warehouse_tag': 'CBTAG_6F4922F45',
                'warehouse_note': 'Gryphon, and the pair of white kid gloves in one hand, and Alice was beginning very angrily, but.',
                'warehouse_status': 'open',
                'weight': '99',
                'quantity': '67',
                'dimension_width': '99',
                'dimension_length': '99',
                'dimension_height': '99',
                'operation_note': 'By the time he had a VERY turn-up nose, much more like a star-fish,\' thought Alice. \'I\'ve so often.',
                'status': 'NEW',
                'remove': 0,
                'created_at': '1985-10-28 07:15:38',
                'updated_at': '2003-07-29 22:59:59',
                'version': '4.0'
            },
            {
                'id': 20,
                'store_id': 1,
                'manifest_id': 2,
                'manifest_code': 'VA1234',
                'package_id': 3,
                'package_code': 'PB_0000000000',
                'package_item_id': null,
                'tracking_code': 'TK1F0E3DAD99908',
                'order_ids': null,
                'weshop_tag': 'WS1F0E3DAD99908',
                'warehouse_alias': 'WS_HN',
                'warehouse_tag': 'CBTAG_1F0E3DAD9',
                'warehouse_note': 'Alice again. \'No, I give you fair warning,\' shouted the Queen, tossing her head to feel which way.',
                'warehouse_status': 'close',
                'weight': '99',
                'quantity': '1',
                'dimension_width': '99',
                'dimension_length': '99',
                'dimension_height': '99',
                'operation_note': 'Queen: so she sat down and cried. \'Come, there\'s no name signed at the thought that it would be.',
                'status': 'NEW',
                'remove': 0,
                'created_at': '1980-09-12 20:46:30',
                'updated_at': '1987-05-28 03:13:23',
                'version': '4.0'
            }
        ],
        '_links': {
            'self': {
                'href': 'http://weshop-4.0.api.vn/v1/tracking-code?p=1'
            },
            'next': {
                'href': 'http://weshop-4.0.api.vn/v1/tracking-code?p=2'
            },
            'last': {
                'href': 'http://weshop-4.0.api.vn/v1/tracking-code?p=10'
            }
        },
        '_meta': {
            'totalCount': 200,
            'pageCount': 10,
            'currentPage': 1,
            'perPage': 20
        }
    }
};
