export const MockResponse = {
    'success': true,
    'message': 'success',
    'data': {
        '_items': [
            {
                'id': 1000,
                'tracking_code': 'TKB706835DE79A2',
                'product_id': null,
                'order_id': null,
                'quantity': null,
                'weight': null,
                'dimension_l': null,
                'dimension_w': null,
                'dimension_h': null,
                'manifest_id': 2,
                'manifest_code': 'VA1234',
                'purchase_invoice_number': null,
                'status': '1',
                'created_at': '2005-03-13 13:17:39',
                'updated_at': '2016-02-25 18:48:37'
            },
            {
                'id': 999,
                'tracking_code': 'TK9AB0D88431732',
                'product_id': 20,
                'order_id': 4,
                'quantity': 11,
                'weight': 98,
                'dimension_l': 86,
                'dimension_w': 11,
                'dimension_h': 91,
                'manifest_id': 1,
                'manifest_code': 'RVS789',
                'purchase_invoice_number': '9AB0D88431732957A618D4A46',
                'status': '1',
                'created_at': '2009-01-11 10:37:52',
                'updated_at': '1979-12-17 14:55:33'
            },
            {
                'id': 998,
                'tracking_code': 'TKEC5AA0B784608',
                'product_id': null,
                'order_id': 6,
                'quantity': null,
                'weight': null,
                'dimension_l': null,
                'dimension_w': null,
                'dimension_h': null,
                'manifest_id': 2,
                'manifest_code': 'VA1234',
                'purchase_invoice_number': null,
                'status': '1',
                'created_at': '2013-07-22 04:35:51',
                'updated_at': '1977-09-29 08:10:23'
            },
            {
                'id': 997,
                'tracking_code': 'TK0B8AFF0438617',
                'product_id': null,
                'order_id': null,
                'quantity': null,
                'weight': null,
                'dimension_l': null,
                'dimension_w': null,
                'dimension_h': null,
                'manifest_id': 2,
                'manifest_code': 'VA1234',
                'purchase_invoice_number': null,
                'status': '1',
                'created_at': '1993-07-21 21:27:50',
                'updated_at': '2012-02-14 06:19:50'
            },
            {
                'id': 996,
                'tracking_code': 'TK2BCAB9D935D21',
                'product_id': 14,
                'order_id': 11,
                'quantity': 11,
                'weight': 52,
                'dimension_l': 76,
                'dimension_w': 73,
                'dimension_h': 95,
                'manifest_id': 2,
                'manifest_code': 'VA1234',
                'purchase_invoice_number': '2BCAB9D935D219641434683DD',
                'status': '1',
                'created_at': '2011-09-18 10:39:26',
                'updated_at': '1988-07-30 05:38:36'
            },
            {
                'id': 995,
                'tracking_code': 'TK934815AD542A4',
                'product_id': 17,
                'order_id': 18,
                'quantity': 20,
                'weight': 68,
                'dimension_l': 50,
                'dimension_w': 94,
                'dimension_h': 6,
                'manifest_id': 2,
                'manifest_code': 'VA1234',
                'purchase_invoice_number': '934815AD542A4A7C5E8A2DFA0',
                'status': '1',
                'created_at': '1997-05-28 23:32:00',
                'updated_at': '2005-09-06 13:14:44'
            },
            {
                'id': 994,
                'tracking_code': 'TK7B13B2203029E',
                'product_id': null,
                'order_id': null,
                'quantity': null,
                'weight': null,
                'dimension_l': null,
                'dimension_w': null,
                'dimension_h': null,
                'manifest_id': 1,
                'manifest_code': 'RVS789',
                'purchase_invoice_number': null,
                'status': '1',
                'created_at': '1995-04-14 02:44:42',
                'updated_at': '2011-10-13 11:35:35'
            },
            {
                'id': 993,
                'tracking_code': 'TK860320BE12A1C',
                'product_id': null,
                'order_id': null,
                'quantity': null,
                'weight': null,
                'dimension_l': null,
                'dimension_w': null,
                'dimension_h': null,
                'manifest_id': 1,
                'manifest_code': 'RVS789',
                'purchase_invoice_number': null,
                'status': '1',
                'created_at': '2010-06-07 08:30:52',
                'updated_at': '1978-07-25 06:36:43'
            },
            {
                'id': 992,
                'tracking_code': 'TK692F93BE8C7A4',
                'product_id': null,
                'order_id': null,
                'quantity': null,
                'weight': null,
                'dimension_l': null,
                'dimension_w': null,
                'dimension_h': null,
                'manifest_id': 3,
                'manifest_code': 'HNC555',
                'purchase_invoice_number': null,
                'status': '1',
                'created_at': '1993-06-10 00:40:43',
                'updated_at': '1994-10-08 13:28:06'
            },
            {
                'id': 991,
                'tracking_code': 'TK4FAC9BA115140',
                'product_id': 10,
                'order_id': 2,
                'quantity': 12,
                'weight': 70,
                'dimension_l': 27,
                'dimension_w': 47,
                'dimension_h': 27,
                'manifest_id': 2,
                'manifest_code': 'VA1234',
                'purchase_invoice_number': '4FAC9BA115140AC4F1C22DA82',
                'status': '1',
                'created_at': '1995-11-19 01:32:33',
                'updated_at': '2016-06-28 22:06:07'
            },
            {
                'id': 990,
                'tracking_code': 'TKA1140A3D0DF1C',
                'product_id': 15,
                'order_id': 12,
                'quantity': 3,
                'weight': 31,
                'dimension_l': 66,
                'dimension_w': 84,
                'dimension_h': 45,
                'manifest_id': 3,
                'manifest_code': 'HNC555',
                'purchase_invoice_number': 'A1140A3D0DF1C81E24AE954D9',
                'status': '1',
                'created_at': '2007-03-26 22:11:05',
                'updated_at': '1981-09-16 14:11:14'
            },
            {
                'id': 989,
                'tracking_code': 'TK9908279EBBF1F',
                'product_id': null,
                'order_id': 5,
                'quantity': null,
                'weight': null,
                'dimension_l': null,
                'dimension_w': null,
                'dimension_h': null,
                'manifest_id': 1,
                'manifest_code': 'RVS789',
                'purchase_invoice_number': null,
                'status': '1',
                'created_at': '2007-08-06 01:00:52',
                'updated_at': '1982-11-13 00:19:06'
            },
            {
                'id': 988,
                'tracking_code': 'TKDF6D2338B2B8F',
                'product_id': null,
                'order_id': 8,
                'quantity': null,
                'weight': null,
                'dimension_l': null,
                'dimension_w': null,
                'dimension_h': null,
                'manifest_id': 1,
                'manifest_code': 'RVS789',
                'purchase_invoice_number': null,
                'status': '1',
                'created_at': '1970-11-12 20:48:56',
                'updated_at': '2012-08-11 10:53:32'
            },
            {
                'id': 987,
                'tracking_code': 'TKFE7EE8FC1959C',
                'product_id': null,
                'order_id': 5,
                'quantity': null,
                'weight': null,
                'dimension_l': null,
                'dimension_w': null,
                'dimension_h': null,
                'manifest_id': 2,
                'manifest_code': 'VA1234',
                'purchase_invoice_number': null,
                'status': '1',
                'created_at': '2010-05-20 21:56:25',
                'updated_at': '1999-02-25 07:57:03'
            },
            {
                'id': 986,
                'tracking_code': 'TK54A367D629152',
                'product_id': null,
                'order_id': 5,
                'quantity': null,
                'weight': null,
                'dimension_l': null,
                'dimension_w': null,
                'dimension_h': null,
                'manifest_id': 3,
                'manifest_code': 'HNC555',
                'purchase_invoice_number': null,
                'status': '1',
                'created_at': '2003-01-01 14:23:56',
                'updated_at': '1998-10-02 19:56:01'
            },
            {
                'id': 985,
                'tracking_code': 'TKD93ED5B6DB83B',
                'product_id': null,
                'order_id': null,
                'quantity': null,
                'weight': null,
                'dimension_l': null,
                'dimension_w': null,
                'dimension_h': null,
                'manifest_id': 3,
                'manifest_code': 'HNC555',
                'purchase_invoice_number': null,
                'status': '1',
                'created_at': '2007-08-04 03:53:06',
                'updated_at': '2002-02-04 21:39:54'
            },
            {
                'id': 984,
                'tracking_code': 'TK6AAB1270668D8',
                'product_id': 13,
                'order_id': 14,
                'quantity': 31,
                'weight': 13,
                'dimension_l': 95,
                'dimension_w': 21,
                'dimension_h': 39,
                'manifest_id': 1,
                'manifest_code': 'RVS789',
                'purchase_invoice_number': '6AAB1270668D8CAC7CEF2566A',
                'status': '1',
                'created_at': '1978-02-04 10:05:18',
                'updated_at': '1987-06-25 08:18:46'
            },
            {
                'id': 983,
                'tracking_code': 'TKFEC8D47D412BC',
                'product_id': 4,
                'order_id': 1,
                'quantity': 48,
                'weight': 1,
                'dimension_l': 5,
                'dimension_w': 13,
                'dimension_h': 100,
                'manifest_id': 3,
                'manifest_code': 'HNC555',
                'purchase_invoice_number': 'FEC8D47D412BCBEECE3D9128A',
                'status': '1',
                'created_at': '1972-04-03 02:30:56',
                'updated_at': '1988-03-04 21:26:39'
            },
            {
                'id': 982,
                'tracking_code': 'TK287E03DB1D99E',
                'product_id': null,
                'order_id': null,
                'quantity': null,
                'weight': null,
                'dimension_l': null,
                'dimension_w': null,
                'dimension_h': null,
                'manifest_id': 2,
                'manifest_code': 'VA1234',
                'purchase_invoice_number': null,
                'status': '1',
                'created_at': '2013-11-13 18:34:00',
                'updated_at': '2003-06-01 21:53:31'
            },
            {
                'id': 981,
                'tracking_code': 'TKD79AAC075930C',
                'product_id': null,
                'order_id': null,
                'quantity': null,
                'weight': null,
                'dimension_l': null,
                'dimension_w': null,
                'dimension_h': null,
                'manifest_id': 2,
                'manifest_code': 'VA1234',
                'purchase_invoice_number': null,
                'status': '1',
                'created_at': '2011-04-03 07:07:12',
                'updated_at': '1975-01-26 10:57:58'
            }
        ],
        '_links': {
            'self': {
                'href': 'http://weshop-4.0.api.vn/v1/draft-package-item?p=1'
            },
            'next': {
                'href': 'http://weshop-4.0.api.vn/v1/draft-package-item?p=2'
            },
            'last': {
                'href': 'http://weshop-4.0.api.vn/v1/draft-package-item?p=50'
            }
        },
        '_meta': {
            'totalCount': 1000,
            'pageCount': 50,
            'currentPage': 1,
            'perPage': 20
        }
    }
};
